### ISSUE TITLE
RUN_ALL_SERVICE_TESTS is undocumented and barely used.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1183]
For some reason we have this:

https://github.com/redhat-developer/odo/blob/78a050bcf771aedeba9778e8b762c026eff7dbba/tests/e2e/service_test.go#L37

We don't use it in Travis CI, nor is there any documentation.

I believe we should remove this and run all the service tests by default. The reasoning is that running the tests locally it should automatically run ALL the tests as it won't be 100% the same as those tests being ran on Travis or other platforms.

If we decide to actually keep it, we need documentation or at least the variable be enabled by default within Makefile.

**Comment by amitkrout** [comment]
Good catch!!!

Context ```odo service create with a spring boot application``` is never executed in travis-ci with each pr we send. Probably it was intentional just to reduce test time cost or might be something else. IMO lets keep it for each pr so that the service operation will also be tested on that template too.

I am in the favor of keeping the env ```RUN_ALL_SERVICE_TESTS``` so that we can get more control over choosing the test to execute. Add the env variable ```RUN_ALL_SERVICE_TESTS``` in .travis.yaml or Makefile which ever is convenient to enable the full test in ci. Must needed documentation ofcourse.

**Comment by geoand** [comment]
I can provide info on why we have this :)

The reason I don't want to run that test, is that it will take forever to finish. And it will take forever to finish because Spring Boot applications has a large number of dependencies making s2i take a long time to complete.

I'm all for changing things, but IMO this should not be run as part of a standard PR build

**Comment by kadel** [comment]
tests were refactored
/close
