### ISSUE TITLE
connection checks

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1588]
Commands that don't require cluster should work even "offline"

We need to remove the connection check that we have there for every command. And use it only for the commands that actually require to communicate with the cluster.

Commands that require connection:
 - `odo push`
 - `odo component delete`
 - `odo service *`
 - `odo link *`
 - `odo project *`
 - `odo app delete`
 - `odo login`
 - `odo logout`

I might be missing something

**Comment by surajnarwade** [comment]
command that require connection check: 

* `odo app delete`
* `odo login`
* `odo logout`

**Comment by kadel** [comment]
> command that require connection check:
> 
> * `odo app delete`
> * `odo login`
> * `odo logout`

thx, added to issues description

**Comment by kadel** [comment]
We can just remove connection check all together.

**Comment by kadel** [comment]
`odo url create` is one of the commands that shouldn't require connection to the cluster

from #1776  (Unable to add url to local config if not connected to cluster)




`odo url create` doesn't need to communicate with the cluster. It needs to work even if user is not logged in or the cluster is not reachable.



```
▶ odo component create nodejs mynode --project myproject
 ✓  Checking component
 ✓  Checking component version
Please use `odo push` command to create the component with source deployed

# simulating situation where I'm not logged into the cluster
▶ export KUBECONFIG=/tmp/non-exsisting

▶ odo url create --port 8080
 ✗  invalid configuration: no configuration has been provided
Please login to your server:

odo login https://mycluster.mydomain.com
```

**Comment by kadel** [comment]
Before jumping into the coding, let's create two lists of the commands. One with all the commands that require cluster connection, other for all the commands that don't need a cluster.

**Comment by cdrage** [comment]
@kadel 

Here's a list:

List of commands that need connection:

 - [ ] `odo component delete`
 - [ ] `odo component link *`
 - [ ] `odo component log`
 - [ ] `odo component push`
 - [ ] `odo component unlink`
 - [ ] `odo component update`
 - [ ] `odo component watch`
 - [ ] `odo component describe` (maybe?)
 
 - [ ] `odo service *`
 - [ ] `odo project *`
 - [ ] `odo app delete`
 - [ ] `odo login`
 - [ ] `odo logout`
 - [ ] `odo app *`
 - [ ] `odo catalog *`

List of commands that dont need connection check:

 - [ ] `odo component create`
 - [ ] `odo component delete`
 - [ ] `odo config *`
 - [ ] `odo preference *`
 - [ ] `odo utils *`
 - [ ] `odo version`

Feel free to edit my post if I'm missing something.

I need clarifying on `odo component describe` however as I'm unsure if it should require a connection check or not (do we actually check the cluster too I wonder?)

**Comment by cdrage** [comment]
@kadel @surajnarwade I went through each of the commands that don't need connection check and found that there we no needed changes...

Let me know what other commands do not need connection checks?

**Comment by kadel** [comment]
List looks good.

**Comment by cdrage** [comment]
@kadel 

We can close this then as I've checked each command and none do any checks. :+1:

**Comment by kadel** [comment]
```
▶ odo component create
 ✗  invalid configuration: no configuration has been provided
Please login to your server:

odo login https://mycluster.mydomain.com

```


```
▶ odo url create --port 8080
 ✗  invalid configuration: no configuration has been provided
Please login to your server:

odo login https://mycluster.mydomain.com
```

**Comment by cdrage** [comment]
@kadel Woops. Sorry about that, was testing against totally the wrong binary :man_shrugging:

**Comment by cdrage** [comment]
@kadel So from my findings (in particular `odo component create`).

The connection would be needed in order to retrieve the list of images available to use on OpenShift, as well as what project (and application) to deploy the component too..

This specifically applies to interactive mode. However, we do not need that for non-interactive.

Just my notes ^^

**Comment by kadel** [comment]
We can keep the cluster connection requirement for `odo component create` for now.

**Comment by cdrage** [comment]
@kadel I've checked the other commands (using the whole `export KUBECONFIG=/tmp/foobar`) and no other commands need changing.

**Comment by kadel** [comment]
For `odo url create` ports should be checked against ports in LocalConfig.


`odo component create` I think that the biggest issue will be that we still need to fetch information about ports from the cluster see https://github.com/openshift/odo/pull/1828. So we need to keep the connection check there

**Comment by girishramnani** [comment]
the `odo url create` doesn't require connection check #1828

**Comment by girishramnani** [comment]
so essentially after the above PR is merged, we can remove check from `odo url create` as well. and thats the only thing left

**Comment by dharmit** [comment]
My understanding after reading the above comments is that the only thing pending is to remove connection check for `odo url create` which was supposed to be removed by #1828 as @girishramnani pointed but that's not the case because when I try to do `odo url create` from the `master`, it still reports:
```sh
$ odo url create url
 ✗  invalid configuration: no configuration has been provided
Please login to your server: 

odo login https://mycluster.mydomain.com

```

**Comment by dharmit** [comment]
I'm looking for a way to make `odo url create` not require active connection to the cluster because based on what I understand, it's not possible to do that if we want it to support `-o json` at some point.

In `Validate` function, we check for the value of `OutputFlag` https://github.com/openshift/odo/blob/c23e542340155a888f24953508462e965478ba30/pkg/odo/cli/url/create.go#L93-L95
which is set in `Complete` function as a part of setting the context https://github.com/openshift/odo/blob/c23e542340155a888f24953508462e965478ba30/pkg/odo/cli/url/create.go#L60

So, unless we can get the `OutputFlag` value using the cobra command and without using the `o.Context`, I don't see how we can get rid of the requirement of a context.

@girishramnani @cdrage @mik-dass can you suggest something?

**Comment by girishramnani** [comment]
If I am not wrong isnt url create declarative now which means it just creates the url in the config and `odo push` does the rest?

**Comment by girishramnani** [comment]
And we now generate the url without checking with the server for collisions so any reason we cannot support `-o json`?

**Comment by mik-dass** [comment]
>  I don't see how we can get rid of the requirement of a context.

I don't understand what is meant by the `context` here.

**Comment by dharmit** [comment]
@girishramnani 
> If I am not wrong isnt url create declarative now which means it just creates the url in the config and odo push does the rest?

It is declarative (based on the definition of declarative you mentioned). However, it does need an active connection with the OpenShift cluster to create a URL. The requirement is to make it not depend on an active connection any more. If you do an `export KUBECONFIG=/tmp/nosuchfile` or `odo logout` and try to do `odo url create`, that would fail.

> And we now generate the url without checking with the server for collisions so any reason we cannot support -o json?

I don't think there's any reason for not having it in already except that it might have been missed while adding `-o json` support for other commands. Pretty sure a PR would pop-up sooner rather than later.

@mik-dass 
> I don't understand what is meant by the context here.

By `context` I mean: https://github.com/openshift/odo/blob/c23e542340155a888f24953508462e965478ba30/pkg/odo/cli/url/create.go#L50
which is a part of the `URLCreateOptions` struct. As per my understanding, as long we are using a `genericclioptions.Context`, we can't remove the dependency on an active OpenShift cluster.

Now, in place of `genericclioptions.Context`, we could use `config.LocalConfigInfo`. But that's not sufficient here because we use: https://github.com/openshift/odo/blob/c23e542340155a888f24953508462e965478ba30/pkg/odo/cli/url/create.go#L93-L95

**Comment by mik-dass** [comment]
> As per my understanding, as long we are using a genericclioptions.Context, we can't remove the dependency on an active OpenShift cluster.

I would suggest removing the connection check from the context itself because in such cases it doesn't seem to make sense. Or am I missing something?

**Comment by kadel** [comment]
> I would suggest removing the connection check from the context itself because in such cases it doesn't seem to make sense. Or am I missing something?

+1
I think that we can remove the connection check altogether. If a command requires the connection to the cluser it will fail in later stages. 



 

> It is declarative (based on the definition of declarative you mentioned). However, it does need an active connection with the OpenShift cluster to create a URL.

It should not. The `odo url create` command just modifies the local config. It shouldn't touch cluster.
@dharmit Is it doing something with the cluster?

**Comment by dharmit** [comment]
@mik-dass @kadel I think this commit https://github.com/dharmit/odo/commit/982b1c00fb3168b76116595956cf89738029efc1 resonates with what you guys suggested about "removing connection checks". Does it?

**Comment by dharmit** [comment]
> @mik-dass @kadel I think this commit [dharmit@982b1c0](https://github.com/dharmit/odo/commit/982b1c00fb3168b76116595956cf89738029efc1) resonates with what you guys suggested about "removing connection checks". Does it?

After doing this, `odo url create` works if `odo` is not connected to cluster, i.e., after doing `odo logout`. But it fails if KUBECONFIG doesn't exist, i.e., if I do `export KUBECONFIG=/no/such/path` and then do `odo url create`, it fails with:
```sh
$ odo url create url
 ✗  invalid configuration: no configuration has been provided
Please login to your server: 

odo login https://mycluster.mydomain.com
```
which is because of: https://github.com/openshift/odo/blob/3d64ea8e4ce413ff612c46423f470f977385d110/pkg/occlient/occlient.go#L231-L234
What do you recommend? @mik-dass @kadel

**Comment by mik-dass** [comment]
> After doing this, odo url create works if odo is not connected to cluster, i.e., after doing odo logout. But it fails if KUBECONFIG doesn't exist, i.e., if I do export KUBECONFIG=/no/such/path and then do odo url create, it fails with:

Can we just exclude the `url create` command from the connection check?

**Comment by dharmit** [comment]
After a talk with @mik-dass I pushed https://github.com/dharmit/odo/commit/9efa40bf58c905bda8279522e21793c429783979. However, https://github.com/openshift/odo/issues/1588#issuecomment-526521539 is still showing up. In the past, I got #1758 merged because it could work with the help of `LocalConfigInfo` which does not look possible in this case since we check for `-o json` flag with the help of a `Context`.

**Comment by cdrage** [comment]
IMO let's keep the connection check for `odo logout` at least as that makes sense. Despite the name connection check, the function looks to be checking if the directory actually exists / is valid.. so that makes sense.

All other commands we should still remove the check however.

**Comment by kadel** [comment]
Why we can't just remove connection check?  We can simply remove the check from https://github.com/openshift/odo/blob/master/pkg/occlient/occlient.go#L292

With the new workflow, I don't think that we need it anymore.

**Comment by dharmit** [comment]
I've finally opened #2078. This thing is probably easy to implement but difficult to have consensus on! :smile:

**Comment by kadel** [comment]
#2078 just removes the global check. 
We will still need to handle the connections error somehow to print the nice message. But it should be done on a per-command basis.

**Comment by dharmit** [comment]
Closing this because the scope of this issue was to remove connection checks before GA which has been done. Further task of adding connection checks and/or messages will be worked upon in #2157.
