### ISSUE TITLE
prevent unnecessary deployment triggers

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1633]
Even if config has not been changed new deployment is triggered because odo changes the order of env variables in DC definition.

<img width="981" alt="Screenshot 2019-04-18 at 17 39 06" src="https://user-images.githubusercontent.com/57206/56373365-0fbc5180-6201-11e9-90ec-b0aa21435fce.png">

**Comment by jorgemoralespou** [comment]
This should be easy if instead of injecting ENVs we create a configMap and we inject all envs from the config map. This configMap should be done for everything odo internal (like the variables shown here). 

Still, we should allow a user to inject configuration as an ENV and we still need to prevent re-ordering of the environment variables, although at least for the common scenario of bare `odo` this would not be a problem.

**Comment by kadel** [comment]
> Still, we should allow a user to inject configuration as an ENV and we still need to prevent re-ordering of the environment variables, although at least for the common scenario of bare `odo` this would not be a problem.

yep, we need to figure out why odo generated env vars each time in a different order, this will resolve a lot of our issues.

**Comment by mik-dass** [comment]
My findings till now:
1. As @kadel suggested, Openshift is smart enough to detect no changes in the DC. Thus if config is not changed, update does nor trigger new deployment.

But three things always change regardless of a new deployment or no new deployment.
Status.observedGeneration, metaData.generation and metaData.resourceVersion. 
The generation numbers always increase by two.

2. If there is a change in the config, other fields change along with the above mentioned ones.

3. The `c.appsClient.DeploymentConfigs(c.Namespace).Update(currentDC)` in PatchCurrentDC does not return the new DC with the updated Status.LatestVersion. That number changes after the new deployment is completed successfully. Thus in case of no config change, no new deployment is triggered and thus `WaitAndGetDC` keeps waiting until timeout.

**Comment by kadel** [comment]
> * If there is a change in the config, other fields change along with the above mentioned ones.
> *

what other fields?

**Comment by mik-dass** [comment]
> what other fields?

Depends on what was changed in the config. If max memory is changed in config, then fields related to that will be changed in the spec etc

**Comment by kadel** [comment]
> > what other fields?
> 
> Depends on what was changed in the config. If max memory is changed in config, then fields related to that will be changed in the spec etc

anything else in the status is not changed?

How does `oc rollout status` works, does it face the same problems?

**Comment by mik-dass** [comment]
> anything else in the status is not changed?

In case of no config changed, no.

> How does oc rollout status works, does it face the same problems?

My findings were based on `oc get dc <dc-name>`. Let me try out the rollout command and share the findings

**Comment by mik-dass** [comment]
Interestingly the field `Status.observedGeneration` doesn't change if we pass the same dc retrieve (without any modification) to the update call. Thus we can detect if the dc was updated or not by this field.

But in our case, this field changes, because while creating or updating the dc, the call `generateSupervisordDeploymentConfig` doesn't fill up all the fields. Some of these fields e.g `dnsPolicy ` are filled automatically by the server. 

So every time we are calling update, the server detects the absence of these fields in the new dc and thus the field `observedGeneration` increases in value indicating that a new dc was detected. But the deployment doesn't get triggered though, probably because the main resource related fields are the same.

**Comment by mik-dass** [comment]
`oc apply` doesn't act smart in the case of 500Mi=512000Ki. New deployment is not triggered in this case but `oc apply` says that the deployment was configured with new values. So I guess fields matching won't work unless we bring each relative field to the same unit and compare.

**Comment by mik-dass** [comment]
The commands like `oc rollout` and `oc apply` all will fail in a like 500Mi to 512000Ki. So we need to come up with some other mechanism.

**Comment by mik-dass** [comment]
https://github.com/openshift/origin/blob/69c55bf03b7ea5e016221170da740297c5acbb22/pkg/apps/util/util.go#L262 

Openshift detects whether to deploy anew deployment or not by comparing the two dcs. We have to modfiy our existing code base to prevent unnecessary deployments.
