### ISSUE TITLE
Flags naming and description issues in help message

### ISSUE THREAD

**Issue by rhuss** [openshift/odo#1671]
[kind/bug]

## What versions of software are you using?
- Operating System: macOs
- Output of `odo version`: 1.0.0-beta1

## How did you run odo exactly?

`odo`

## Actual behavior

* Options are printed starting randomly with lower and uppercase.
* The gramatical form is not consistent. E.g. it should be all starting with a verb (like in "Show help for odo" instead of "help for odo")
* Inconsisten naming of flags `--alsologtostderr` vs. `--log_dir` or `--log_backtrace_at`. Tbh, both forms are uncommon, flags/options are typically using a hyphen as separator (e.g. `--also-log-to-stderr`, `--log-dir`)
* The usage e.g. of the logging options is confusing, and some of them like --log_backtrace_at more sounds like an internal debugging option not useful for a user.
* --uncomplete vs --incomplete ? Why is this an option and not a command ?
* what are "V logs" ?
* What is a "pattern=N settings" ?
* Why `--y` and `-y` ? And not `--yes` ? When its specific to completion, why not an extra command.
* Log related option shoudl be all prefixed with `log` so that they appear together in the help.
* Detangle options to specify a *single* action, not combined action like "alsologtostderr". This can easily reduce the UX surface e.g. `--log-to=stderr,file`
* `--log_dir string  If non-empty, write log files in this directory`. What happens when its empty ? Can it be empty ?

```
Flags:
      --alsologtostderr                  log to standard error as well as files
      --complete                         Install completion for odo command
  -h, --help                             help for odo
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default false)
      --skip-connection-check            Skip cluster check
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --uncomplete                       Uninstall completion for odo command
  -v, --v Level                          log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
  -y, --y                                Don't prompt user for typing 'yes' when installing completion
```

**Comment by kadel** [comment]
All good points, each one should be addressed.
Thank you @rhuss

**Comment by cdrage** [comment]
I had previously been working on this (fixing some of the capitalization), so I'll take this up.

**Comment by cdrage** [comment]
TODO's:

- [ ] Options are printed starting randomly with lower and uppercase.
- [ ]  The gramatical form is not consistent. E.g. it should be all starting with a verb (like in "Show help for odo" instead of "help for odo")
- [ ]  Inconsisten naming of flags `--alsologtostderr` vs. `--log_dir` or `--log_backtrace_at`. Tbh, both forms are uncommon, flags/options are typically using a hyphen as separator (e.g. `--also-log-to-stderr`, `--log-dir`)
- [ ]  The usage e.g. of the logging options is confusing, and some of them like --log_backtrace_at more sounds like an internal debugging option not useful for a user.
- [ ]  --uncomplete vs --incomplete ? Why is this an option and not a command ?
- [ ]  what are "V logs" ?
- [ ]  What is a "pattern=N settings" ?
- [ ]  Why `--y` and `-y` ? And not `--yes` ? When its specific to completion, why not an extra command.
- [ ]  Log related option shoudl be all prefixed with `log` so that they appear together in the help.
- [ ]  Detangle options to specify a *single* action, not combined action like "alsologtostderr". This can easily reduce the UX surface e.g. `--log-to=stderr,file`
- [ ]  `--log_dir string  If non-empty, write log files in this directory`. What happens when its empty ? Can it be empty ?

**Comment by cdrage** [comment]
Hey @rhuss I have solved (most) of your concerns via #1690 and #1689 

With regards to the following:

 what are "V logs" ?
  What is a "pattern=N settings" ?

**Both of these are the default descriptions for glog and unfortunately we cannot change it without forking the library**


  Why --y and -y ? And not --yes ? When its specific to completion, why not an extra command.
  --uncomplete vs --incomplete ? Why is this an option and not a command ?

**This is the default description for autocompletion support which we unfortunately cannot change without forking the library**

**Comment by rhuss** [comment]
> **Both of these are the default descriptions for glog and unfortunately we cannot change it without forking the library**

That is unfortunate, and tbh I don't consider this good style by a library to hook into the global state of an application. Maybe one could submit a PR upstream to make this behaviour at least optional/configurable ?

> This is the default description for autocompletion support which we, unfortunately, cannot change without forking the library

What I don't get why this must be a global option available to every command. IMO this should be only an option when creating autocompletion.

While we are at it, why isn't there a dedicated `completion` command like for kubectl and other tools, but an option `--completion`? Does this global option even make sense when used with any other command ? You should really reconsider this, as this is a fundamental break in the UX when you allow an option as a command (i.e. you can use `odo --completion` without error and without specifying a command). This is very confusing, especially as --completion opens up a dialog wizard for writing out files. In good UNIX tradition, I found it better to just spit out the commands to stdout so that anyone can include it on their own in their startup scripts, which might be highly customized as well. Personally, I wouldn't allow anyone else to modify my startup shell scripts. 

Just tried that feature:

```
Install completion for odo? yes
Installing...
Done!
```
Hmm.

* Where was it installed ?
* odo <TAB> doesn't work after that for me (only after starting a new shell)
* when I move 'odo' then the startup script is broken

```
odo compgen:96: no such file or directory: /Users/roland/bin/odo
compgen:96: no such file or directory: /Users/roland/bin/odo
compgen:96: no such file or directory: /Users/roland/bin/odo
```

This can easily happen when you e.g. call `./odo --complete` before you move it to the target directory.

`./odo --uncomplete` also doesn't work anymore afterwards and because you don't know where it was installed you have a hard time to undo this (finally found it in ~/.zshrc and not in `~/.zsh-custom` where I would expect it and which is much easier to maintain as its only about removing a file and not regexp replacing in an existing file). Btw even that `./odo --uncomplete` didn't remove anything, it still says 

```
Uninstall completion for odo? y
Uninstalling...
Done!
```

When I move back the binary to its original location it --uncomplete works again.

tbh, I think that completion functionality as is is not robust enough for delivering within a product.

I wouldn't open the box of the Pandora and manipulate startup scripts which can be highly customized. Instead, I would go the kubectl route to easily add the user the completion code herself because then she knows where it is included and also keeps the full ownership of her shell startup scripts.

Plus the usage as options is super ugly and doesn't fit in the overall scheme.

**Comment by kadel** [comment]
@cdrage 

I think that we could forbid glog to inject those flags and use our own flags to set loglevel no?
I would be surprised if glog is so rigid that it doesn't allow to change this.


For the completion, we don't have to have a flag on the root level. We could easily do something like `odo complete --install` `odo complete --uninstall`


@rhuss 
If I remember correctly https://github.com/posener/complete library because it allows us to write the logic that suggests values in Go, instead of bash.  This is much easier to maintain and test.
kubectl is using standard cobra feature that requires to write this logic in bash. For example, this is how the function for suggesting container names looks like https://github.com/kubernetes/kubernetes/blob/e0a1913837af097559e45b10d98ee27ed8be8b37/pkg/kubectl/cmd/cmd.go#L185

**Comment by cdrage** [comment]
After https://github.com/openshift/odo/pull/2160 being merged in, I feel as though this should now be medium priority.

The only thing left, would be moving the completion functions to `odo completion` or `odo utils completion`.

**Comment by kadel** [comment]
> fter #2160 being merged in, I feel as though this should now be medium priority.
> 
> The only thing left, would be moving the completion functions to `odo completion` or `odo utils completion`.

/close
