### ISSUE TITLE
odo watch hangs in Terminal as Default Behavior 

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#1723]
Running an `odo watch` currently hangs in the terminal as follows:

```
odo watch
Waiting for something to change in <LOCAL COMPONENT DIRECTORY FOR USER>

```

`odo watch` also hangs in the terminal after a change is pushed:

```
Pushing files...
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✓  Building component
Waiting for something to change in <LOCAL COMPONENT DIRECTORY FOR USER>
```

As a default behavior, `odo watch` should not hang in the terminal after being run. There could maybe be a flag to designate that an `odo watch` continuing to rub should be the behavior expected.

## Which functionality do you think we should update/improve?
`odo watch`

## Why is this needed? 
To improve the user experience of `odo watch`. Having to run a `ctrl+c` to get out of `odo watch` after running an `odo watch` and then having to run `ctrl+c` after a change is pushed is unnecessary.

**Comment by cdrage** [comment]
@danielhelfand If we were to change the functionality of `odo watch` to not hang in the terminal, wouldn't that be the exact same functionality as `odo push` ? 

Essentially.. if we were to incorporate these changes, I don't think we would even *need* `odo watch` anymore and we could just do a flag to `odo push`, for example `odo push --watch` ?

That's just my thoughts. 

Ping @girishramnani @kadel @surajnarwade

**Comment by danielhelfand** [comment]
@cdrage Maybe I'm misinterpreting exactly how to use `odo watch`, but my thought would be that the functionality of `odo watch` can still be running in the background but not hanging in the terminal. For instance, if I wanted to use that same terminal where `odo watch` has been run to make a quick edit to a file via the terminal. Then, when a save occurs, an `odo push` happens. 

I'm not sure what the best workflow would be for this, but I would think that `odo push --watch` would maybe make sense so that an auto push would occur after the initial push. Not sure exactly how that would affect making changes to the component configuration (i.e., if a push should happen every time a config update occurs), but I do like that the idea of being able to auto push for source updates.

**Comment by cdrage** [comment]
So in a nutshell:

`odo create` - to initially create the component / application you're using
`odo push` - to initially push the code / push it manually
`odo watch` - for odo to automatically watch the directory and push automatically (iterative development with code)

`odo watch` is meant to be ran in the background, yes, however, in a separate terminal in order to see any changes to the directory and what's being pushed. It's one of the commands that's being fundamentally used with VSCode / IDE plugins.

**Comment by danielhelfand** [comment]
So is there a reason for it hanging in the terminal? For instance, if I `ctrl+c` out of  an `odo watch` after running, it still updates me what it's pushing if I change something. Then it hangs again after notifying me.

I'm wondering why it cannot avoid hanging all together and just notify when it is pushing something and then also include details on what is being changed.

**Comment by cdrage** [comment]
@danielhelfand Now *that* is a weird bug. After you Ctrl+C it should automatically exit and no longer update... Ctrl+C should exit it completely. We have no background Go routines, so there shouldn't be any updating.

The hanging is necessary since we wouldn't want it running as a daemon in the background / background task, having it doing via CLI allows `odo` to be kept active until there is a change on the local filesystem. It doesn't use any

**Comment by danielhelfand** [comment]
I see. My other [issue](https://github.com/openshift/odo/issues/1722) now makes a lot more sense. I understand why `odo watch` does this now. But yes, this is something I have been experiencing. I can close this and open a bug issue. I'll reference this issue in the write up. Thanks for your help with all this.
