### ISSUE TITLE
Control aspects of component PVC creation

### ISSUE THREAD

**Issue by geoberle** [openshift/odo#1777]
[kind/Enhancement]
I would love to see some control over the automatically created PVC during "odo create / odo push". Especially the following aspects should be controllable by flags:
* storage class
* PVC size
* PVC name

Why the storage class? There might be multiple storage classes with different quotas available to a developer. It is beneficial for sure to let the developer pick the storage class.

Why the PVC size? As far as I know, the default size is 1GB. Depending on the use case that might be too much and also limiting if one has to cope with tight storage quotas.

Why the PVC name? Depending on the storage class and dynamic provisioning engine, the length of the PVC and PV might be a limiting factor. e.g. NetApps trident backs PVs with qtrees and a length limit applies. With the current naming convention of ODO and (to a higher degree) trident itself, it is very likely that the limit is exceeded and the PVC remains unbound. I'm not suggesting a naming convention change in ODO but rather full control of the PVC name via a cli flag.

**Comment by kadel** [comment]
It makes sense to have this configurable, I agree. I remember that we discussed this already somewhere, but can't find the issue :-(

We need to figure out how to do this properly. This is something that should be hidden for normal uses. Most of the users won't care about this, and they shouldn't even need to know that there is PVC. Or what PVC is.

We might put this as `odo preference` option. This would mean that that user can configure this for his odo instance. I would like to avoid adding this as a flag for `odo component create`

- `odo preference set SourceVolumeSize 1G`
- `odo preference set SourceVolumeClass standard`

or

- `odo preference set SourcePVCSize 1G`
- `odo preference set SourcePVCClass standard`

Not sure about the name. Currently, we automatically generate its name based on the component name and application name to ensure that there are no collisions. Allowing users to modify name will create another overhead to handle collisions. 
If just the length of the generated name is the issue, I would look for another pattern for PVC name generation to limit the length, rather than allowing the user to control it.


ping @jorgemoralespou

**Comment by jorgemoralespou** [comment]
One aspect that might be important, given that in Online environments PVCs are expensive, could be to have a shared PVC for all the odo pods, although that would only work with RWX type of PVCs, which is not what most Online platforms provide, which typically is Block.

This is going to be a limiting factor for the future, and some alternatives should need to be looked at moving forward, as we moved into adding server side components.

For now, I would think that the name should not be configurable but related to the component, but the size should be. Not sure about the PVC class, as that depends on what's available on the cluster, and a `standard` class could not be there AFAIK. The size for sure, should be configurable, with the smaller default possible, so we can then provide better behavior on those platforms that allocate provisioning dynamically and can fit smaller sizes. Claiming for 1Gi by default means that even if there's smaller storage, it would not be used. But in any case, I think that the best fit size is something that we will come up as we use the tool more, so sounds reasonable to have a default that will guarantee it works.

For the preference name, I would not use PVC as that seems very related to Kube knowledge, but Volume.

**Comment by jorgemoralespou** [comment]
Related to the name, AFAIK, the name is for the PVC which is a Kubernetes object, but the name for the underlying storage being provisioned by the storage platform is not dictated in any way and assigned by the storage platform itself (I might be wrong). I just tested this on one of my clusters and while the PVC hadd `<component-name>-<app-name>-s2idata` as name, the PV had something like `pvc-15370130-8724-11e9-942e-028eac496444`

@geoberle if you see something different with your storage provider, can you detail more?

**Comment by geoberle** [comment]
You are right. Kubernetes does not enforce a specific PV name depending on the PVCs name. Bu it’s up to he storage provider o pick the name for a dynamically provisioned PV. In case of https://github.com/NetApp/trident the PVCs name influences the PV name and that influences the name of the backing storage, which is length limited. To be honest I’m not aware of any other storage backend doing got that way. All the others I know work as in your example where the PV name is some sort of UUID.

**Comment by geoberle** [comment]
just wanted to follow up on this issue. do you need additional information or discussion to establish a valid usecase?
