### ISSUE TITLE
use "referenceOwner" for all resources related to component

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1793]
All resources created by odo, should have "referenceOwner" that points to the main component "DC".
This will ensure that if DC is removed from the console, oc, or any other mechanism not controlled by odo, the rest of the resources, like PVC, Service, Route etc..  is garbage collected by the platform.

/priority medium
/milestone 1.0

**Comment by girishramnani** [comment]
@kadel , what should be the best way to test it? just checking that the dc has the `referenceOwner` or not? because if that's set correctly then the rest of the behavior is part of openshift

**Comment by kadel** [comment]
> @kadel what should be the best way to test it? just checking that the dc has the `referenceOwner` or not? because if that's set correctly then the rest of the behavior is part of openshift

yep, that could be enough

**Comment by kadel** [comment]
@girishramnani do we have any progress on this?

**Comment by girishramnani** [comment]
the analysis was done, now I am going to implement it as I close off debug

**Comment by girishramnani** [comment]
My analysis that could be helpful - 
1 - document to refer https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
2 - to make the garbage collector work you would need to add `Propogation policy` to `background` for the deploymentConfig ( DC would be the top level config which everyone will refer ). I have a branch that does this https://github.com/girishramnani/odo/tree/feature/reference_owner if you want to take a look
3 - then add the referenceOwner to everything but storage as we want that to be around even on deletion.

cc @kadel

**Comment by dharmit** [comment]
> just checking that the dc has the `referenceOwner` or not? because if that's set correctly then the rest of the behavior is part of openshift

I think this holds true if the DC is going to spin up the those things. Quoting the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents) referenced in https://github.com/openshift/odo/issues/1793#issuecomment-528221344:
> In 1.8, Kubernetes automatically sets the value of ownerReference for objects created or adopted by ReplicationController, ReplicaSet, StatefulSet, DaemonSet, Deployment, Job and CronJob.

I created a component and URL from the nodejs-ex project and found that only the replication controller has its `ownerReferences` set as the DC being spun up. The pod has replication controller as its `ownerReference`. But the other objects don't have any `ownerReferences` set. These objects include:
- ImageStream
- Secret
- Route
- Service

I've not tried to set `ownerReferences` field for a DC as discussed in https://github.com/openshift/odo/issues/1793#issuecomment-517268666 but if that was true, shouldn't we see `ownerReferences` value set already? I think it's more than just setting this value for a DC because we're creating a DC, Service, Route, and ImageStream separately. 

The ImageStream gets created first, then the DC which spins up RC and pods, and then the Service. It's all happening as a part of `BootstrapSupervisoredS2I` function.

A crazy thought: could we use OpenShift template to spin things up and take care of `ownerReferences` because we can specify component name as the owner for each object being created?

Please correct me if I'm wrong. I'm just starting to get into this things and could be horribly wrong in my understanding. @kadel @girishramnani

**Comment by kadel** [comment]
> These objects include:
> 
> * ImageStream
> * Secret
> * Route
> * Service

Don't forget ServiceInstance

> I've not tried to set `ownerReferences` field for a DC as discussed in [#1793 (comment)](https://github.com/openshift/odo/issues/1793#issuecomment-517268666) but if that was true, shouldn't we see `ownerReferences` value set already? I think it's more than just setting this value for a DC because we're creating a DC, Service, Route, and ImageStream separately.

DC shouldn't have `ownerReference`. It is the other way around,  all other objects that you list should have `ownerReference` pointing to the DC





> A crazy thought: could we use OpenShift template to spin things up and take care of `ownerReferences` because we can specify component name as the owner for each object being created?

We don't need a template for this. We need to move away from OpenShift specific resourced, not add another one.

**Comment by dharmit** [comment]
> Don't forget ServiceInstance

I think we worked on a series of issues to be able to create services independent of context. Do we want to now attach a ServiceInstance to a DC?

PVC as well? Or does that get deleted by itself? I found a PVC lurking around while doing a series of  "`odo push`, `oc get all`, `oc delete`" to  try to understand this issue. But I couldn't reproduce that so I honestly don't know what created that PVC.
 
> DC shouldn't have `ownerReference`. It is the other way around, all other objects that you list should have `ownerReference` pointing to the DC. 

Yes that's what I meant but didn't say explicitly. This is what I understood from the Kubernetes docs. Having an `ownerReferences` in DC sounds counter-productive to what we're trying to achieve here.

> Basically we should set ownersReference to what you found in Replica Controller for all other object created by odo

Ack. However, pods have their `ownerReferences` set to the RC so that's taken care of automatically. In fact, `oc delete dc/<dc-name>` does delete the RC and pods while other resources don't get deleted.

> We don't need a template for this. We need to move away from OpenShift specific resourced, not add another one.

Okay. :joy:

**Comment by dharmit** [comment]
> It depends on which PVC. If it is PVC that is used in every component to hold the source code. If I remember correctly we call it "s2idata" or something like this. Then yes, this should be deleted with DC.

I'm talking about this one. OK, I'll make sure they're deleted with a DC. Thanks for the clarification!
