### ISSUE TITLE
odo forgets environment variable while second push

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1834]
[kind/bug]

## What versions of software are you using?
- Operating System: :penguin: 
- Output of `odo version`: `odo v1.0.0-beta3 (HEAD)`

## How did you run odo exactly?

```
odo create nodejs
odo config set --env FOO=BAR
odo push
oc describe dc <dc_name> // you will see env variables
odo push 
oc describe dc <dc_name> // boom, there's no FOO=BAR
```

## Actual behavior

After second `odo push`, env variable is not there in DC

## Expected behavior

After second `odo push`, env variable should be there in DC

**Comment by kadel** [comment]
Let's start with writing tests that will replicate this, and then implement the fix.

**Comment by dharmit** [comment]
> Let's start with writing tests that will replicate this, and then implement the fix.

@kadel the issue is reproducible and I agree with your idea of starting with writing a test. Or rather a failing test in this case. However, `odo config view` reports the environment variable correctly. We need to execute `oc` commands and parse its output. Do we have any tests that do this right now? Which category of tests would this fall under?

**Comment by kadel** [comment]
> @kadel the issue is reproducible and I agree with your idea of starting with writing a test. Or rather a failing test in this case. However, `odo config view` reports the environment variable correctly. We need to execute `oc` commands and parse its output. Do we have any tests that do this right now? Which category of tests would this fall under?

Yes, we already have tests that execute `oc` commands and parses outputs to verify if everything was set properly.  There is even a small library in tests helpers that wraps `oc` commands in a nice way. Just check existing tests.

I think that you can put this test where we have other `odo push` related tests. cc: @amitkrout

**Comment by dharmit** [comment]
I think that doing `odo push` right after doing the first `odo push` should have not created a new DeploymentConfig in the first place because nothing was changed. It looks to me like the env vars of existing DeploymentConfig were not being used properly and this resulting in `odo` thinking that something changed which resulted in it creating a new pod. https://github.com/openshift/odo/blob/54b9a583f3823ba2b684a327c403f00a46814566/pkg/component/component.go#L1070-L1084
As can be seen above, `evl` contains the env vars but it's not being used when creating `updateComponentParams`.
