### ISSUE TITLE
Binary component push fails with context flag

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1846]
[kind/bug]

## What versions of software are you using?
- Operating System: I tested it on macOS
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo create wildfly javaee-war-test --project myproject --binary tests/examples/binary/java/wildfly/ROOT.war --context tests/examples/binary/java/wildfly/ ✓  Validating component [112ms]
Please use `odo push` command to create the component with source deployed


$ odo push --context tests/examples/binary/java/wildfly/
Validation
 ✓  Validating component [86ms]
 ✓  Checking component [3ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [365ms]
 ✓  Applying configuration [0s]

Pushing to component javaee-war-test of type binary
 ✗  open /Users/amit/go/src/github.com/openshift/odo/tests/examples/binary/java/wildfly/tests/examples/binary/java/wildfly: no such file or directory
```

## Actual behavior
Push fails with context flag

## Expected behavior
Should push binary component 

## Any logs, error output, etc?
Check ```How did you run odo exactly?``` section

**Comment by amitkrout** [comment]
ping @kadel

**Comment by cdrage** [comment]
I can investigate this. I have a feeling it has to do with my changes to `context` and paths...

/assign cdrage

**Comment by girishramnani** [comment]
so essentials whats happening here is that the `componentContext` and `SourceLocation` are joined to get the sourceOsPath.
In this case both are `tests/examples/binary/java/wildfly/ROOT.war` and `tests/examples/binary/java/wildfly` which get appended together generating `tests/examples/binary/java/wildfly/tests/examples/binary/java/wildfly` which doesn't exist

The approach to solve this should be that the `SourceLocation` should be saved as a path relative to `componentContext` because in the end we are joining them both here 
https://github.com/openshift/odo/blob/a15c0615151ed3435c11cb427b9f5a071d800737/pkg/config/config.go#L655

I also feel that there will be multiple places this can be reproduced - not just here

cc @amitkrout @kadel

**Comment by girishramnani** [comment]
https://github.com/openshift/odo/issues/1922#issuecomment-512885702
