### ISSUE TITLE
oc logout Also Logs Out odo

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#1949]
[kind/bug]

When using `odo` and logged into the same cluster as `oc`, running `oc logout` causes `odo` to also be logged out of the OpenShift cluster. This is due to both using the same kube config most likely.

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: `odo v1.0.0-beta3 (c2b402e3)`

## How did you run odo exactly?
`oc login <cluster url> -u user -p password`
`odo login <cluster url> -u user -p password`
`oc logout`
`odo project create project`

## Actual behavior
`odo` responds with ` ✗  Please log in to the cluster`

## Expected behavior
`odo` should still be logged in.

## Any logs, error output, etc?
` ✗  Please log in to the cluster`

**Comment by cdrage** [comment]
`odo login` is an alias for `oc login` and vice-versa with `oc logout` and `odo logout`. This is expected behavior so we align with `oc` being used on same client.

It sucks, but we're stuck with it. Or else there's going to be two different environments between `oc` and `odo`.

What are your thoughts @girishramnani / @surajnarwade ?

**Comment by danielhelfand** [comment]
@cdrage Right, was expecting this to be intentional. I just wanted to report it and see if there had been any thought put into it at this point. I understand that this is somewhat of an edge case that may just have to be lived with.

**Comment by girishramnani** [comment]
For now we cannot change this behaviour. Hence closing this issue.
