### ISSUE TITLE
odo link - display injected env variables

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1964]
Currently, the user doesn't know what environment variables were added by `odo link` command.
Odo should inform users what environments were added to the component.

It could look like this:

-  linking component-service
```
▶ odo link mysql-persistent
 ✓  Service mysql-persistent has been successfully linked from the component python-mysqlpython-edxf

Following environment variables were added to the python-mysqlpython-edxf component:
 - database_name
 - password
 - root_password
 - uri
 - username
```

- linking component-component
```
▶ odo link mybackend
 ✓  Component mybackend has been successfully linked from the component myfrontend

Following environment variables were added to the myfrontend component:
- COMPONENT_MYBACKEND_HOST
- COMPONENT_MYBACKEND_PORT
```

cc: @jankleinert

**Comment by jankleinert** [comment]
@kadel Thanks for opening this! This would definitely address my concerns. 

I'm also going submit a PR for the docs to explain in more detail how the component-component link env variables are constructed (for example, I incorrectly thought it was always COMPONENT_BACKEND_HOST / COMPONENT_BACKEND_PORT regardless of the component name, which I now know is wrong.) 

The concept of linking components in odo is also probably a good topic for a blog post; I'll add that to my to-do list too!

Finally, and unrelated to odo, I'm going to raise an issue with the ocp 4.x web console because it makes it appear as if the keys in the secret data are all caps (e.g. DATABASE_NAME) even when they are actually lowercase (e.g. database_name). You can see the correct case in the YAML, but it can be confusing if you just look at the Secret page.

**Comment by dharmit** [comment]
I'm going through the code around this right now but I'm not able to understand why below function https://github.com/openshift/odo/blob/baf308be44d1d0b648e3040e0b3d08af7921196d/pkg/odo/cli/component/common_link.go#L112
takes the execution to https://github.com/openshift/odo/blob/baf308be44d1d0b648e3040e0b3d08af7921196d/pkg/occlient/occlient.go#L2295

@kadel @girishramnani @mik-dass @cdrage can someone help me understand this? :disappointed:

**Comment by mik-dass** [comment]
`operation` is a variable in commonLinkOptions
https://github.com/openshift/odo/blob/baf308be44d1d0b648e3040e0b3d08af7921196d/pkg/odo/cli/component/common_link.go#L106

and it is assigned the value of linkSecret
https://github.com/openshift/odo/blob/baf308be44d1d0b648e3040e0b3d08af7921196d/pkg/odo/cli/component/link.go#L85
