### ISSUE TITLE
Overlapping messages when pushing git component

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1971]
There are overlapping messages when running `odo push` on git component.

"Creating component" and "Waiting for build to finish" 

![git-component](https://user-images.githubusercontent.com/57206/62289187-5a837180-b45e-11e9-957e-5110712eb188.gif)

And when everything is finished "Creating component" message is there twice

<img width="351" alt="Screenshot 2019-08-01 at 13 14 31" src="https://user-images.githubusercontent.com/57206/62289196-5eaf8f00-b45e-11e9-8982-eba1c49f8c3e.png">

**Comment by amitkrout** [comment]
@kadel I have observed it many times and it happens only with git component. Thanks for the issue

**Comment by girishramnani** [comment]
The reason for this to happen is because 
- `Creating component` spinner starts due to `CreateFromGit`
- `Waiting for build to finish` spinner starts but this doesn't stop the parent spinner hence both show
- `Waiting for build to finish` stops but then actually the `\r\n` occurs and the `Creating component` shows up and hence we see that
- `Creating component` spinner stops

So questions
1 - the solution for this should be that even though we see two message constantly switching if we dont overlap then its fine? - could probably be solved by an extra (\r\n) 
2 - or the solution is to somehow show the `waiting for build to finish` as a sub-spinner ( which is not possible ) hence we either need to remove the `Waiting for build to finish` or add the feature in the upstream library?
cc @kadel

**Comment by kadel** [comment]
The output should have the same basic structure as a local component.


So something like this:

```
Validation
 ✓  Checking component [342ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [1s]
 ✓  Applying configuration [15826ns]

Building component java-spring-boot-yelj of type git
 ✓ Triggering build from git
 ✓  Building component [1m]
```


We probably should remove  `Deploy` and `Build` from `CreateFromGit` function.
Creat should just prepare resources, not trigger build. Build and Deploy and triggered outside of the CreateFromGit funciton

**Comment by girishramnani** [comment]
Got it

**Comment by mik-dass** [comment]
During second push, the overlapping messages are `Waiting for build to finish` and `Applying Configuration`
