### ISSUE TITLE
Odo index file stores absolute filepath for files

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1975]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora
- Output of `odo version`:

## How did you run odo exactly?
```
odo create java
odo push
```
Check the `.odo/odo-file-index.json`, it will have files stored as absolute path which would 
- if someone checks in the index file and another user gets that repo then the first push will always be a full build
- makes the project less portable. If a developer moves the project around, the index breaks 
- unnecessary prefix `/Users/<user>` for each filepath. Contributes to size of the index file

**Comment by girishramnani** [comment]
Opened a draft pr for people to try and also so we could discuss the best way to handle the breaking change

**Comment by girishramnani** [comment]
Maybe we can even version the index file? 
We can use the same base struct as we use that we use for json output?

**Comment by kadel** [comment]
> Maybe we can even version the index file?
> We can use the same base struct as we use that we use for json output?

One thing to keep in mind is that this file can be always recomputed. It doesn't hold any important information. Even if the structure changes, we can delete the file and recreate it. The only input that this will have is that it will trigger push even if files were not changed.

**Comment by dharmit** [comment]
I have a question which is not exactly related to the absolute vs. relative path discussion.

Is the index file going to be tracked in a git repo? If it is, are we assuming that two developers working on same project will also work on same OpenShift cluster? Because if they work on different OpenShift clusters, wouldn't the json file make odo believe that some files are already pushed to the cluster when they actually aren't?

Am I thinking correctly or am I missing something? :thinking:
