### ISSUE TITLE
Windows binary tar.gz file has nothing inside

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2085]
[kind/bug]

Odo 1.0.0-beta5 release missing windows executable. 
`.tar.gz` file is to small to be correct one.

**Comment by cdrage** [comment]
Fixed.

Last release `make cross` failed when deploying since bash functions were required and `Makefile` was being ran with `sh`.

You should see it now on the release :)

![Screenshot from 2019-09-04 13-36-00](https://user-images.githubusercontent.com/6422176/64277687-f64e4480-cf18-11e9-911f-935342b37f23.png)
