### ISSUE TITLE
odo link Fails to Link Java Component to Node.js Component

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#2224]
[kind/bug]

I am trying to run `odo link` to link two components running in the same OpenShift project. The first component is a [Java application](https://github.com/openshift-evangelists/Wild-West-Backend). The second component is a [Node.js application](https://github.com/openshift-evangelists/Wild-West-Frontend). 

The Node.js component serves as the frontend for an application, and the Java component is a backend API. In previous versions of `odo`, these components could be linked using `odo link`, but now running `odo link` with these components causes the Node.js application to stop running. 

I will describe the exact way I ran `odo` below, but the Node.js application works on the first `odo push`. Running `odo link` results in the Node.js application displaying the `Application is not available` error message from OpenShift.

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: `odo v1.0.0-beta6 (0cdcc908)`

## How did you run odo exactly?

Order of commands based on number ordering

### Java app

1. `odo create java backend --binary target/wildwest-1.0.jar`
2. `odo push`

### Node.js app

3. `odo create nodejs frontend`
4. `odo url create frontend`
5. `odo push`

### Linking

6. `odo link backend --component frontend --port 8080`

## Actual behavior

Running `odo link` displays successful output:

```
$ odo link backend --component frontend --port 8080
 ✓  Component backend has been successfully linked from the component frontend

Following environment variables were added to frontend component:
- COMPONENT_BACKEND_HOST
- COMPONENT_BACKEND_PORT
```

Clicking on url of application results in getting the generic OpenShift error:

```
Application is not available
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.
```

## Expected behavior

In previous versions of `odo`, the application components would be linked, and the Node.js component would communicate successfully with the Java component.

## Any logs, error output, etc?

Logs from frontend pod:

```
2019/10/02 12:55:13 [go-init] No pre-start command defined, skip
2019/10/02 12:55:13 [go-init] Main command launched : /opt/odo/bin/supervisord -c /opt/odo/conf/supervisor.conf
time="2019-10-02T12:55:13Z" level=info msg="create process:run" 
time="2019-10-02T12:55:13Z" level=info msg="try to start program" program=run 
time="2019-10-02T12:55:13Z" level=info msg="success to start program" program=run 
+ set -eo pipefail
+ echo 'Setting up'
+ /opt/odo/bin/s2i-setup
Setting up
+ set -eo pipefail
+ mkdir -p /tmp
+ touch /tmp/.dummy
+ mkdir -p /tmp/src/
+ touch /tmp/src/.dummy
+ [[ /tmp != *\/\s\r\c* ]]
+ mkdir -p /tmp/src
+ touch /tmp/src/.dummy
+ mkdir -p /opt/app-root/src
Running
+ echo Running
+ /opt/odo/bin/run
+ set -eo pipefail
+ export ODO_UTILS_DIR=/opt/odo
+ ODO_UTILS_DIR=/opt/odo
+ export ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
+ ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
++ /opt/odo/bin/getlanguage
+ IMAGE_LANG=nodejs
+ '[' '!' -z nodejs ']'
+ exec /opt/odo/language-scripts/nodejs/dev-run
+ cd /tmp/src
+ NODE_ENV=development
+ DEBUG_PORT=5858
+ DEBUG_MODE=true
+ export GIT_COMMITTER_NAME=unknown
+ GIT_COMMITTER_NAME=unknown
+ export and GIT_COMMITTER_EMAIL=unknown@localhost
+ GIT_COMMITTER_EMAIL=unknown@localhost
+ git --version
git version 1.8.3.1
++ node --version
Using Node.js version: v10.16.3
+ echo -e 'Using Node.js version: v10.16.3'
+ echo -e Environment:
+ echo -e '  NODE_ENV=development'
Environment:
  NODE_ENV=development
+ echo -e '  DEBUG_PORT=5858'
+ echo -e '  DEBUG_MODE=true'
  DEBUG_PORT=5858
  DEBUG_MODE=true
++ id
Running as user uid=1000520000(1000520000) gid=0(root) groups=0(root),1000520000
Launching via npm...
+ echo -e 'Running as user uid=1000520000(1000520000) gid=0(root) groups=0(root),1000520000'
+ echo 'Launching via npm...'
+ '[' true == false ']'
+ exec npx nodemon --inspect=5858
time="2019-10-02T12:55:14Z" level=debug msg="wait program exit" program=run 
  Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.

time="2019-10-02T12:55:31Z" level=info msg="program stopped with status:exit status 0" program=run 
time="2019-10-02T12:55:31Z" level=info msg="Don't start the stopped program because its autorestart flag is false" program=run 
```

**Comment by kadel** [comment]
/kind bug
/priority high

Verified.

The nodejs source code is stored in `/tmp/src`, the problem is that this directory is not backed by any volume, so once the container is restarted for some reason, like when the variables for linking are added, the source code inside the container is lost. :-(

I will look into this, we need to make this work.

A quick temporary workaround is to run `odo push -f` after `odo link`.

**Comment by danielhelfand** [comment]
@kadel Thanks for the explanation. I'll note that this most recently worked in `odo v1.0.0-beta5`, so assuming the change happened recently.

**Comment by jankleinert** [comment]
Can we get something like this scenario added to pre-release testing so that if something changes that stops this from working, it doesn't go live?

**Comment by kadel** [comment]
> Can we get something like this scenario added to pre-release testing so that if something changes that stops this from working, it doesn't go live?

I was actually under the impression that we have this scenario in our tests :-(
I will have to check how is it that this got in. And ether fix it or add it to our tests.

**Comment by kadel** [comment]
/remove-priority high
/priority critical

This is more serious than this. This also impacts Java components.
Every time the NodeJS or Java component is restarted the source code from the container is lost. 

In Java, it is not that obvious, as compiled jar file is kept, so application is running, but when you edit a file and do `odo push` you won't see the changes as the compilation will fail.


The solution that I wanted to implement is to simply add volume for the directory where the source code is kept (`/tmp/src`), it solves the problem for NodeJS, but it completely breaks Java as assemble in openjdk s2i image is executing `chmod` command on `tmp/src`  and this fails as you can't change permissions of the  directory where volume is mounted :-(

I need to look for other solutions.
Right now I see two options.
 - Go back to what we have been doing (backup /tmp/src/ to a different directory, and restoring it when the container starts)
 - Replace Java s2i scripts with our version that runs `chmod /tmp/src/* instead of `chmod /tmp/src`


If we go with the second option it will mean that we are completely customizing s2i images for both Java and NodeJS. I would consider building a new special version of s2i image for odo, that we will push into the quay.io and use it instead of the s2i builder images that are found in the cluster.

cc: @girishramnani @sspeiche @jorgemoralespou

**Comment by girishramnani** [comment]
> If we go with the second option it will mean that we are completely customizing s2i images for both Java and NodeJS. I would consider building a new special version of s2i image for odo, that we will push into the quay.io and use it instead of the s2i builder images that are found in the cluster.

I would prefer to not use this approach as it makes the user has to use different image streams over what the cluster has to provide.

**Comment by kadel** [comment]
> > If we go with the second option it will mean that we are completely customizing s2i images for both Java and NodeJS. I would consider building a new special version of s2i image for odo, that we will push into the quay.io and use it instead of the s2i builder images that are found in the cluster.
> 
> I would prefer to not use this approach as it makes the user has to use different image streams over what the cluster has to provide. And this doesn't work well with air gapped clusters as well

But on the other side, it creates a predictable setup. We will be able to test the exact combination of the builder image and odo as the user will use.

**Comment by girishramnani** [comment]
There should be better approach because this is quite similar to have a server side odo component

**Comment by jorgemoralespou** [comment]
This is a result of not involving the image teams into helping solving this out :-( 
We don't have much time to fix for GA, but we should start working with all the image teams (specially java and node.js) so that the images can work with s2i and odo in a seamless way.
For now, I would think that probably, similar to what we might need to inject the s2i assemble scripts in the image with a modified version, although I don't think that adding yet another volume is a good solution anyways, as many users would have a limitation on volumes, but for now seems as the only possible approach.

I agree with girish than rather than creating our own images we need to work with the image builders so that the images work for both scenarios, avoiding complexity on odo configuration and supporting the images we provide and that are installed on the cluster.

**Comment by kadel** [comment]
> I don't think that adding yet another volume is a good solution anyways, as many users would have a limitation on volumes, but for now seems as the only possible approach.

Technically it is not going to me new PersitentVolume,  we are using one PVC  and use subPath to mount it into the multiple paths.

**Comment by jorgemoralespou** [comment]
Didn't know this was possible. Sound good then.

**Comment by girishramnani** [comment]
one of the issues with mounting the `/tmp/src` is the `chmod` issue that @kadel mentioned above ( i.e. we cannot chmod on the mount point of a volume ). so after some discussion. A solution for this could be to mount the parent `/tmp` directory which is recognised as `S2I_DESTINATION_DIR` https://github.com/jboss-openshift/cct_module/blob/1ff1d9637979b1d0b116f247640f5330b20a7a45/jboss/container/s2i/core/api/module.yaml#L17

Above solution will resolve this problem but we would have to still have to resolve the https://github.com/openshift/odo/issues/2248 ( delete not propogating )

Some would argue that `/tmp` dir is used by other applications too and might fill up the volume between restarts which could increase the memory footprint. The solution to that is to set the S2I_DESTINATION_DIR to something like `/tmp/odo` but currently we want to not break  assumptions there are made by the s2i devs when deciding the defaults.

**Comment by cdrage** [comment]
There is another scenario that fails, specifically, URL creation.

In this scenario, even after an `odo push -f`, we require to *delete* the URL and then recreate it just to access the service.

To replicate:

```sh
git clone https://github.com/openshift/nodejs-ex
cd nodejs-ex
odo create nodejs
odo push
odo url create myurl

# Visiting the URL is fine here...

odo service create mongodb-persistent --plan default --wait -p DATABASE_SERVICE_NAME=mongodb -p MEMORY_LIMIT=512Mi -p MONGODB_DATABASE=sampledb -p VOLUME_CAPACITY=1Gi
odo link mongodb-persistent

# Visiting the URL no longer works

odo push -f 

# Visiting the URL still does not work 

odo url delete myurl
odo url create myurl
odo push

# Visiting the URL works again

```

**Comment by kadel** [comment]
Hmm, so it looks like that we might not be able to have volumeMount on `/tmp`, the java builds are failing on 
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:00 min
[INFO] Finished at: 2019-10-04T14:32:09Z
[INFO] Final Memory: 49M/181M
[INFO] ------------------------------------------------------------------------
INFO Copying deployments from target to /deployments...
'/tmp/src/target/spring-boot-rest-http-1.5.17-5-SNAPSHOT.jar' -> '/deployments/spring-boot-rest-http-1.5.17-5-SNAPSHOT.jar'
rm: cannot remove '/tmp/hsperfdata_jboss': Directory not empty
```

**Comment by kadel** [comment]
> avoiding complexity on odo configuration and supporting the images we provide and that are installed on the cluster.

the problem is that in the current situation we can't avoid adding more complexity on odo :-(
Depending on what builder image is being used the odo will have to prepare different setup.

**Comment by jorgemoralespou** [comment]
Yes, but we need to lay out a plan to minimize this moving forward. It is what it is today, but we need to not be this way sooner than later.

**Comment by kadel** [comment]
> Yes, but we need to lay out a plan to minimize this moving forward. It is what it is today, but we need to not be this way sooner than later.

Yes, I agree. I'm trying to find a solution that would work today. Moving forward we need to stop relying on the s2i scripts.

**Comment by kadel** [comment]
This problem was introduced in https://github.com/openshift/odo-init-image/pull/27 when we started overriding the NodeJS and Java assemble and run scripts.

The `dev-assemble` script introduced in https://github.com/openshift/odo-init-image/pull/27 was supposed to speed up the build by not copying files from `/tmp/src` to `/opt/app-root/src`. 
`npm i` command and application itself were executed from the `/tmp/src`. But because there is not volume mounted on`/tmp/src` the content of this directory is lost when the pod is restarted (linking needs to restart the Pod, because it adds env variables to the container).

Simply mounting volume to `/tmp/src` doesn't help, as it will break the OpenJDK based images. (see https://github.com/openshift/odo/issues/2224#issuecomment-538340473)

I tried to revert back to use the `assemble` script from NodeJS images. But this creates a problem when using `DEV_MODE` to allow remote debugging. When `DEV_MODE=true` the assemble scripts sometimes fails on 
```
rm: cannot remove '.npm/_cacache/content-v2/sha512': Directory not empty
```
The last operation that `assemble` in NodeJS images does is cleaning cache with `rm -rf .npm`.
For some reason, this sometimes fails with above error. 
Interestingly every time it failed was when `DEV_MODE` was set to `true`.

I'm currently investigating why is this happening. 
I'm not that good with NodeJS :-( 
@lholmquist , can you please help me figure out what might be wrong? Have you seen this error before?
