### ISSUE TITLE
Being able to manually set a ODO_BOOTSTAPPER_IMAGE via `odo config`

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2424]
/kind enhancement

## Which functionality do you think we should update/improve?

When we release a new update to the bootstrapper image, the *only* way to update is:

```
export ODO_BOOTSTRAPPER_IMAGE=registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.0.1
odo delete
odo push
```

Alternatively, we should be able to set it via: `odo config` and NOT have to recreate the image.

For example:

```
odo config set BootstrapperImage registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.0.1
odo push --config # like it's said in the output whenever you do an update
```

## Why is this needed? 

Need this for backwards compatibility when releasing a new image.

**Comment by kadel** [comment]
Changing the bootstrapper image is something that the user should never do. 
`ODO_BOOTSTRAPPER_IMAGE` is there only for use in testing, to make it easier for us to test an image before we do a release. Users should never change the image.

If you put it into the config as you propose it will never get updated with a new odo release, and the user will have to update it in the config.

The initImage is tied to given odo cli release, and outside of us testing it should be never changed to what is specified in odo. odo doesn't guarantee compatibility of you use different initImage from what is specified for given odo release.

**Comment by cdrage** [comment]
@kadel My reasoning is backwards compatibility. If there was a bug in the odo init image, but not in the CLI, I'd make sense to update the init image. As of right now, if Red Hat were to release an errata, we cannot provide a solution to the current bug other than: "Download the new release". Do you think we should keep it that way?

**Comment by kadel** [comment]
Not sure if I understand what you mean.

So if there is bug in init image and we need to release a new version you would like to just build the image, and then tell users to do `odo config set BootstrapperImage ... ` instead of downloading new odo binary?
How users will know when they need to do it? If someone configures a new image like this how we will make sure then when we release a new complete odo version they will start using new image?


I think that this creates a lot more problems than it solves. The mean tool that users are using is CLI. The initImage is just an implementation detail. If there is a bug in the image I think that it makes complete sense to release a new odo binary as this is the only way how we can ensure that everything was properly tested.


> As of right now, if Red Hat were to release an errata, we cannot provide a solution to the current bug other than: "Download the new release". Do you think we should keep it that way?

I really think that this is the correct and right way to do it.

**Comment by cdrage** [comment]
Going to close this as @kadel 's points are clear, this discussion helped clarify a bunch of things!
