### ISSUE TITLE
Do not allow combination of --context with (project, app and component) flags

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2443]
based on: https://github.com/openshift/odo/issues/2387#issuecomment-553866802_

It can be confusing when `--context` flag is used together with one or more `--project` `--app` `--component` flags.

We should add a check that doesn't allow the use of `--context` with `--app` or `--project` or `--component`.

**Comment by girishramnani** [comment]
this will break alot of our tests, as currently we are using `--context` with `--project` and `--app` for `odo create`. and maybe it makes sense to have this possible for `odo create` because a user might want to use a specific app and a project while creating the `config.yaml` in the `--context` directory? @kadel

**Comment by kadel** [comment]
> this will break alot of our tests, as currently we are using `--context` with `--project` and `--app` for `odo create`.

yes, we have to fix those tests!




> and maybe it makes sense to have this possible for `odo create` because a user might want to use a specific app and a project while creating the `config.yaml` in the `--context` directory?

That is a good point. For `odo component create` it makes sense to combine `--context` and with `--project` and/or `--app`. But not for anything else.
