### ISSUE TITLE
provide admin commands to install operators and one-off setup 

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2464]
[kind/Feature]

## Which functionality do you think we should add?
To start **using** `Operators` on openshift, an administrator needs to install operators first. We can provide the feature to interactively install these operators easily ( only possible for an admin user ).
Also install necessary operator like Service Binding Operator as part of a one-off `setup` command.

**Comment by dharmit** [comment]
AFAIK, our users are mostly  going to have CRC on their laptops or a OCP 4.x cluster managed by the admins. So, should we just mention this in documentation instead of having commands in odo to install operators? Do we want to have installation of Operators as a part of odo tool? Or do we want to focus on spinning up service from installed operators? WDYT @kadel @girishramnani ?

**Comment by kadel** [comment]
We should focus on spinning up services from installed operators.
Similarly, how we are not installing ServiceCatalog Brokers because that is cluster admin's job we don't need to spend much time on providing commands for installing Operators, as this is usually cluster admin's job.
This might change in the future, as there are some plans to allow user accounts to install certain verified operators.
This is still valid concern, but it is not priority right now.

**Comment by dharmit** [comment]
@kadel @girishramnani I think we're in consensus to not do admin activities like installing operators using odo. Should we close this?
