### ISSUE TITLE
Implement devfile support

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#2467]
Implement devfile support per agreed upon implementation plan https://github.com/openshift/odo/issues/2290

This is needed to support new model for inner loop (hot redeploy) touch points and further work on supporting specific runtimes.

**Comment by kadel** [comment]
The first stage will be just consuming devfiles (`odo push`).
A detailed description will be in https://github.com/openshift/odo/issues/2470

**Comment by jichenjc** [comment]
@kadel could you please help to show where we can find when the devfile will be in release ? I was told odo-init-image will be replaced by this devfile feature, can I know when it might happen? Thanks

**Comment by girishramnani** [comment]
This issue is quite huge as we can observe the https://github.com/openshift/odo/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fdevfile 
but currently features that are essential to have feature parity that are left are https://github.com/openshift/odo/issues?q=is%3Aopen+is%3Aissue+label%3Arequired-for-v2+label%3Aarea%2Fdevfile

Now mostly all of them have people assigned to them (except 1) and many have PRs as well. so this epic will be done for 2.0 milestone.

**Comment by girishramnani** [comment]
the feature parity so far is attained and we have another epic https://github.com/openshift/odo/issues/3782 for follow up for devfile support.
Closing this issue as the AC is achieved.
