### ISSUE TITLE
prefix for odo link env variables

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2543]
## User Story
- As an odo user
- I want to be able to specify a prefix that will be applied to the env variable name injected into the component when the component is linked to the other component

## Acceptance Criteria
- `odo link` should have a flag to specify the prefix
- the prefix should be recorded in a local config
- when `odo push` is executed all injected env variables (related to link) should be prefixed with the specified prefix
- `odo describe` should pick up the env variables exposed by the services and show them with the prefix. 

## Prerequisites
#2400

## Links
Feature request: https://github.com/openshift/odo/issues/2369

/kind user-story
/area link

**Comment by kadel** [comment]
this issue is blocked on #2400

**Comment by girishramnani** [comment]
one thing to add to the AC here is 
- `odo describe` should pick up the env variables exposed by the services and show them with the prefix. This is important because we need to show the user the prefixed env variables exposed. 
and I feel `odo describe` is a good place to do this.

We can have this as a separate user story or in this itself

**Comment by kadel** [comment]
> one thing to add to the AC here could be @kadel
> 
> * `odo describe` should pick up the env variables exposed by the services and show them with the prefix. This is important because we need to show the user the prefixed env variables exposed.
>   and I feel `odo describe` is a good place to do this.

👍 this is a good point.
I've added it as an acceptance criteria
