### ISSUE TITLE
Multiple calls to Openshift API to fetch same data.

### ISSUE THREAD

**Issue by adisky** [openshift/odo#2604]
/kind code-refactoring

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
 `odo app describe` 

## Actual behavior
for `odo app describe` command, Multiple calls to fetch the same data. 
This is happening due to non hierarchical nature of structures, e.g. AppSpec(https://github.com/openshift/odo/blob/master/pkg/application/types.go#L16 ) can refer component (https://github.com/openshift/odo/blob/master/pkg/application/types.go#L16) instead of having it as list of strings, similarly component can refer storage structure instead of having as list of strings.
https://github.com/openshift/odo/blob/master/pkg/application/types.go#L16
https://github.com/openshift/odo/blob/master/pkg/component/types.go#L22

There could be a reason of making structures this way, maybe I am not aware of, but i felt having inheritance in structures, would make it less error prone/synced output and non repeated calls to openshift API.

**Comment by kadel** [comment]
You are right. But it will need some lazy loading. Because if you start adding references you can end up fetching a lot of data that you don't need.

Let's say that  `Application` has an array of `Components` structs instead of just listing names and `Components` has array `Storage` structs instead of just names, and also the same for `URL`.

Now If I want to get information about the application and names of the components without any details I'll end up listing data for everything or with uncomplete structures.

But with some kind of lazy loading it would make sense and it would be great.

**Comment by adisky** [comment]
@kadel Agreed, But at some places without using reference we are fetching all data like `odo component list`, https://github.com/openshift/odo/blob/master/pkg/component/component.go#L864, it is calling GetComponent() https://github.com/openshift/odo/blob/master/pkg/component/component.go#L1320, which is populating storage/url's also. Its like if we are referring  `storage` as list of strings, we need to get that information too, its just the way of storing it will differ. 

And listing we are doing manual, with control of what informations we want to present.
https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/list.go#L73 

But i also agree that this is a large refactoring, which could break things and does not require if everything running well :).
