### ISSUE TITLE
`odo catalog list components` should work without cluster

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2740]
It should be possible to list devfile components even if odo is not connected to the cluster

```
 export ODO_EXPERIMENTAL=true
▶ odo catalog list components
 ✗  unable to list imagestreams: Get "<url>": dial tcp <IP>:8443: connect: connection refused.
unable to list imagestreams: Get "<url>": dial tcp <IP>:8443: connect: connection refused
```

Instead of failing, odo can just show a warning that it can't connect to the cluster, and show just devfile components.

/kind bug
/priority low
/area devfile
/area catalog

**Comment by johnmcollier** [comment]
@GeekArthur Your work for https://github.com/openshift/odo/issues/2706 should fix this right?

**Comment by GeekArthur** [comment]
@johnmcollier Yes, this issue is duplicate issue of https://github.com/openshift/odo/issues/2706, and @kadel 's suggestion is same as my fix plan, we all good for this 🚀

**Comment by johnmcollier** [comment]
One thing that I would add to this issue, is if `PushTarget` is set to Docker, maybe omit the message about not being able to connect to the cluster?

**Comment by GeekArthur** [comment]
This is a comment from another issue
> Only retrieve the devfile components when experimental mode is enabled, knowing that odo push with experimental mode currently only supports devfile components

If that's still the case, we can only list devfile components when we turn on Experimental flag since `odo push` with experimental mode currently only supports devfile components, that would make the devfile support features more consistent and avoid the generic error of connecting to the cluster including https://github.com/openshift/odo/issues/2740#issuecomment-601840525
