### ISSUE TITLE
Document all states of the component

### ISSUE THREAD

**Issue by boczkowska** [openshift/odo#2773]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Add documentation about the states of the component

## What is the relevance of it?
More discussion here: https://github.com/openshift/odo/pull/2690#pullrequestreview-383544630

**Comment by dharmit** [comment]
Various possible states for the component:
|State|Meaning|
|------|------------|
|Pushed| Component has been pushed to the remote cluster |
|Not Pushed| Component exists on local disk but has not been pushed to the remote cluster |
|Unknown| Component state could not be determined. Most likely because user is not logged in to the cluster |

@kadel @girishramnani @adisky does above sound good to you folks?

**Comment by boczkowska** [comment]
Docs PR: https://github.com/openshift/openshift-docs/pull/23453

**Comment by dharmit** [comment]
@boczkowska Thanks for the PR! In the PR I see that you've mentioned four states of which the state `Locally Deleted` doesn't make sense to be kept under `odo list`. 
* `odo list`/`odo component list` - the status info showed here is that of the component
* `odo storage list` - the status info showed here is that of the storage connected (if any) to the component
* `odo url list` - the status info showed here is that of the URL created (if any) to access the component.

`Locally Deleted` is not a valid state for a component and it being under the `odo list` section is a bug.

**Comment by dharmit** [comment]
This is already implemented.

/close
