### ISSUE TITLE
Executing run command fails with connect: connection refused

### ISSUE THREAD

**Issue by ajm01** [openshift/odo#2803]
/kind bug

## What versions of software are you using?

**Operating System:**
Linux

**Output of `odo version`:**
odo v1.1.1 (032caa7)

## How did you run odo exactly?
 ./odo push -f -v 4 --show-log --build-command="Builder" --run-command="Run"

## Actual behavior
during the run command:
```
•  Executing run command /artifacts/bin/deploy.sh  ...
I0401 15:00:26.574371   24574 exec.go:23] Executing command [/opt/odo/bin/supervisord ctl stop all] for pod: devfilesrcproj-5f859f9b57-42zkw in container: deploy
Fail to send request to supervisord: Post http://localhost:9001/RPC2: dial tcp [::1]:9001: connect: connection refused
I0401 15:00:26.785257   24574 exec.go:23] Executing command [/opt/odo/bin/supervisord ctl start devrun] for pod: devfilesrcproj-5f859f9b57-42zkw in container: deploy
Fail to send request to supervisord: Post http://localhost:9001/RPC2: dial tcp [::1]:9001: connect: connection refused
devrun: failed [Post http://localhost:9001/RPC2: dial tcp [::1]:9001: connect: connection refused]
 ✓  Executing run command /artifacts/bin/deploy.sh [382ms]
 ✓  Push devfile component devfilesrcproj [1m]
 ✓  Changes successfully pushed to component
I0401 15:00:26.956443   24574 odo.go:80] Could not get the latest release information in time. Never mind, exiting gracefully
```

## Expected behavior
after removing the 'tail' command from the run component in the dev file:
```
 •  Executing run command /artifacts/bin/deploy.sh  ...
I0401 15:07:38.738074   25795 exec.go:23] Executing command [/opt/odo/bin/supervisord ctl stop all] for pod: devfilesrcproj-5c644bd879-lcptd in container: deploy
devrun                                     OK
devdebug                                   OK
I0401 15:07:38.895756   25795 exec.go:23] Executing command [/opt/odo/bin/supervisord ctl start devrun] for pod: devfilesrcproj-5c644bd879-lcptd in container: deploy
devrun: started
 ✓  Executing run command /artifacts/bin/deploy.sh [1s]
 ✓  Push devfile component devfilesrcproj [2m]
 ✓  Changes successfully pushed to component
I0401 15:07:40.174569   25795 odo.go:80] Could not get the latest release information in time. Never mind, exiting gracefully
```

## Any logs, error output, etc?
none that i am aware of

**Comment by anshulvermapatel** [comment]
I can work on this one, can someone assign me to this issue.

**Comment by GeekArthur** [comment]
@ajm01 In order to reproduce this issue properly, can you let me know the following information for clarify:
1. The specific odo group of commands to reproduce instead of the odo command (`./odo push -f -v 4 --show-log --build-command="Builder" --run-command="Run"`) that hit this issue (eg. `odo create` -> `odo url` -> `odo push`) as I would like to reproduce from end-to-end use case perspective
2. Which devfile component type you use 
3. Do you use the devfile from our default registry or you use your own devfile, if you use your own devfile please provide it so that I can use that to reproduce

I find you use odo `v1.1.1`, it would be great you can give a try our latest odo `v1.1.3` to see if you still have the issue as IIRC we delivered some fixed/features regarding odo sync and exec recently and that may or may not resolve this issue

**Comment by GeekArthur** [comment]
@maysunfaisal Is this one already fixed? Seems like there is no update from the issue creator but I believe you know this one as he pings you personally. If it's fixed, please provide some steps/details to reproduce then we can do more investigation.

**Comment by GeekArthur** [comment]
@maysunfaisal @ajm01 Can you guys try the latest master to verify if this issue still exists? We can either add more reproduce steps (issue still exists) or close this issue (issue doesn't exist).

**Comment by ajm01** [comment]
ok, I got the latest master and ran with it - based on my understanding it looks like the issue is resolved in that i am no longer seeing the connection refused message and the push is successful.
