### ISSUE TITLE
Support listing devfile v2 components in odo

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2835]
/kind user-story
/area devfile

## User Story
As a user, I want to be able to list the running devfile components on my system (Either Kube cluster or Docker) and see which devfile they belong to, using `odo list`.

## Acceptance Criteria 
- [x] `odo list` should be able to list all of the running devfile components in a given namespace
- [x] `odo list` should specify which devfile each component is part of (e.g. `openLiberty`, `java-springboot`, etc)
- [x] If running on an OpenShift cluster with both s2i and devfile components, it needs to support listing both

/kind user-story

**Comment by kadel** [comment]
> * [ ]  `odo list` should be able to list all of the running devfile components in a given namespace
> *

Currently `odo list` filters the component based on the application (using `app` or `app.kubernetes.io/part-of` label).  Would we want to do the same?

Each component belongs to the application, and if you do `odo list` it lists components in the current application.

**Comment by dharmit** [comment]
As for the possible state of the component, please refer https://github.com/openshift/odo/issues/2773#issuecomment-610922457.

**Comment by adisky** [comment]
IMO, for devfiles `odo list` should list components from cluster only in the current namespace, `odo describe` should describe component in the current context folder from cluster/local config both. Keeping `odo list` to list down components from cluster would keep it simple and easy to understand.

**Comment by girishramnani** [comment]
Do we need to implement the —all flag and —path flag to support compatibility for vscode?
That would definitely increase the complexity and we need to consider a situation where there are components in path which are deployed on kube using devfile and s2i on openshift.

**Comment by adisky** [comment]
Not sure about the `--path` flag but the flag `--all-apps`  lists ` List all components from all applications for the current set project`.
The first question is do we want to have `app` concept for devfiles?

**Comment by girishramnani** [comment]
we dont have the `app` concept for devfiles, that is one thing we need to address as part of this PR as well. might be a good idea to add that as part of the AC.

**Comment by girishramnani** [comment]
- we would be able to fetch all the components by going over all the deployments ( maybe using a label selector ) searching for `component` label https://github.com/openshift/odo/blob/master/pkg/devfile/adapters/kubernetes/component/adapter.go#L199, might also be a good idea to have `managed-by` label in place like we used to have for openshift components.
- change the odo list output to have `cluster type` as an extra field which could for now have `openshift`, `kubernetes` and `docker/local` value? or have a different table to each of these types like we have for operator services and catalog services.

**Comment by adisky** [comment]
> * we would be able to fetch all the components by going over all the deployments ( maybe using a label selector ) searching for `component` label https://github.com/openshift/odo/blob/master/pkg/devfile/adapters/kubernetes/component/adapter.go#L199, might also be a good idea to have `managed-by` label in place like we used to have for openshift components.
> * change the odo list output to have `cluster type` as an extra field which could for now have `openshift`, `kubernetes` and `docker/local` value? or have a different table to each of these types like we have for operator services and catalog services.

IIUC from a single odo session, i guess it would be difficult to list down from different clusters, if you are thinking to list down locally then an additional field needs to be added locally.

**Comment by girishramnani** [comment]
so I hit an interesting road block on this issue. I realised that we would need to add the `appName` as a metadata on the devfile as this information is not environment specific and needs to be available to someone downloading the component from a repository.
But currently I cannot find a scenario where we are adding things to `devfile.yaml` locally. so just want to confirm that do we need to start doing that now @kadel @elsony .

**Comment by girishramnani** [comment]
so not to make this huge and to maintain compatibility to a certain degree. I will add the app in local env info instead of `devfile`.

**Comment by dharmit** [comment]
Not having app name is something I'm hitting with operator hub integration as well. In the experimental mode, I can start a service from service catalog because we assume the default value for `--app` flag to be `app` if user doesn't provide any.

But if we want to list the services started from service catalog (in experimental mode), we can't do it from a devfile component directory because it doesn't have `app` value. And #3050 is not implemented yet.

I have similar question as @adisky - do we want to have `app` concept?

I see that there's an open issue #3050 about adding `managed-by` label. Does using that for `app` make sense even for devfile components? That's how we segregate resources of a particular app on the cluster right now, IIUC. That would make it cluster specific and we'll again have to resort to _assuming_ default if user doesn't provide any - _assuming_ because unlike `.odo/config.yaml`, a devfile doesn't store info about `app`. So, I go back to the same question - does `app` provide enough value to continue supporting it?

**Comment by girishramnani** [comment]
The biggest problem with removing —app concept will be breaking backward compatibility and to a certain degree asking vscode adapter team to rewrite many modules.

**Comment by dharmit** [comment]
> The biggest problem with removing —app concept will be breaking backward compatibility and to a certain degree asking vscode adapter team to rewrite many modules.

I agree with your point. But moving from s2i to devfile is going to introduce few changes that cause trouble to Adapters, no? Would it be helpful to at least have a discussion about this with them to understand how useful it is for end-users?

**Comment by dgolovin** [comment]
Removing application would require some changes but simplify many things on Adapters side. What we really need is odo supporting devfile component in: odo list, odo describe so we can show them in OpenShift Application Veiw and detect that workspace folder is odo component. 
Currently adapters cannot work with devfile components because:
1. devfile components are not part of `odo catalog list components -o json` output (see https://github.com/openshift/odo/issues/3247) so user cannot pick it as a component type
2. devfile components are not reported in `odo list` 
3. There is no way to detect that workspace folder has devfile component in it (`odo list --path /location` and `odo describe` does not work)

**Comment by girishramnani** [comment]
The 3rd point could be resolved by checking for an existence of devfile.yaml?

**Comment by dgolovin** [comment]
@girishramnani I don't want to relay on the insider knowledge, that would fail for example if you decide to support docker components and configuration is going to be in DOCKERFILE. The best way for IDEs to relay on odo command for component detection, this way we are stay away from implementation details. 
I was thinking that `odo describe` would work but it does not.

So we kind of stuck right now. We can enable Experimental mode, but then Devfile components does not behave the same way as S2I ones. IMO both kinds of component fits perfectly to odo approach they should just be supported throughout all odo commands.

**Comment by girishramnani** [comment]
understood, I am nearly done with this, just need to write tests and we are good to go.
