### ISSUE TITLE
Create docker volumes based off of volumes in devfile

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2849]
/kind user-story

## User Story
As a user, I want the volumes defined in my devfile to correspond to Docker volumes and get mounted in to the containers that require them

## Acceptance Criteria 
- [ ] It should create docker volumes based on the volumes defined in my devfile
- [ ] It should share docker volumes where needed (multiple containers specifying the same volume)

## Links 
- Feature Request: 
- Related issue: 

/kind user-story
/area local
/area devfile

**Comment by maysunfaisal** [comment]
Some things I noticed in master branch:
- when creating component for the first time, any volumes - project/devfile/supervisord should be checked if present for reuse, rather than creating a new volume with the same labels
- when updating component a component, if more than a single volume with the same labels are found, error out. I noticed that when i have two volumes with the same labels, containers can pick any of the volumes and mount it, which is wrong as volume may different data.
