### ISSUE TITLE
"--devfile" support for odo create

### ISSUE THREAD

**Issue by GeekArthur** [openshift/odo#2862]
/kind user-story

## User Story
As a user I want to use my own devfile instead of the devfile from registry, to achieve that I can use `--devfile` to specify my own devfile location 

## Acceptance Criteria 
1. Features
- [x] It should download/copy devfile from the specific location to user's working directory
- [x] --devfile flag value should support both http(s) path and file system path
- [x] Remove --devfile flag for all other commands (eg. `odo url`, `odo push`, `odo delete`, `odo watch`)
- [x] New design of existing devfile support, if user decides to use existing devfile (devfile exists in user's working directory or user specifies the existing devfile via `--devfile` flag) the first argument will be the component name instead of component type, and user can pass in the component name directly in direct mode

2. Handling errors
- [x] Validate `--devfile` flag value (eg. error out if the devfile path doesn't exist)
- [x] If an existing devfile already exists in the user's working directory, show an error to avoid overriding user's existing devfile

/kind user-story

**Comment by johnmcollier** [comment]
Copying my comment from the PR, with respect to component naming with `--devfile`:

If --devfile is set, and the user passed in an arg to odo create, can we just interpret that as the component name, rather than component type?

That is, if --devfile is set, then the argument after odo create becomes the component name, rather than the component type. e.g.:

```
$ odo create mycomp --devfile devfile.yaml
```

Would create a component from the devfile.yaml with name mycomp

and

```
$ odo create nodejs mycomp
```

would still create a nodejs component named mycomp

**Comment by GeekArthur** [comment]
Redesign discussion is under PR: https://github.com/openshift/odo/pull/3118

**Comment by GeekArthur** [comment]
Design is finalized under the PR: #3118
