### ISSUE TITLE
Flakey test observed in devfile describing urls

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2890]
/kind bug

## What versions of software are you using?

**Operating System:**
Supported
**Output of `odo version`:**
master
## How did you run odo exactly?
https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_url_test.go#L154

**Comment by kadel** [comment]
@amitkrout what is the failure? Can you please provide failure logs or links to failed runs? 

This is not enough information.
/triage needs-information

**Comment by amitkrout** [comment]
This issue is based on the report https://gist.github.com/kadel/2570427b9113ea0bb546f45723b7a643. Even i was not sure about reason, so i tried it locally couple of times and none of the time i could reproduce it. For now the best way to get the failure log is to wait for CI failure in the same spec.

**Comment by kadel** [comment]
> For now the best way to get the failure log is to wait for CI failure in the same spec.

no need to wait for it to happen just use https://search.svc.ci.openshift.org/ to search through logs

**Comment by yangcao77** [comment]
This issue has been fixed in this PR: https://github.com/openshift/odo/pull/2762
And the reason why this is happening is described here: https://github.com/openshift/odo/pull/2762#issuecomment-608642267

I've never seen this test failed after this PR has been merged. 
Same for #2891  and #2892 
We can close these three issues.

**Comment by kadel** [comment]
@yangcao77 thank you.
Closing this 
/close
