### ISSUE TITLE
Container initiailization support

### ISSUE THREAD

**Issue by elsony** [openshift/odo#2936]
/kind user-story

## User Story
As a stack creator, I want to initialize my the container that I defined in the devfile 2.0.  
Devfile 2.0 providers ability to execute commands based on lifecycle events.

## Acceptance Criteria 
- [ ] It should follow the specification as defined in https://github.com/che-incubator/devworkspace-api/issues/32 to support execution of the commands based on the events.
   -  [ ] implement `preStart`according to [lifecycle_events.md](https://github.com/openshift/odo/blob/master/docs/proposals/lifecycle_events.md)
   -  [x] implement `postStart` according to [lifecycle_events.md](https://github.com/openshift/odo/blob/master/docs/proposals/lifecycle_events.md) -  done in https://github.com/openshift/odo/pull/3533
   -  [ ] implement `preStop`according to [lifecycle_events.md](https://github.com/openshift/odo/blob/master/docs/proposals/lifecycle_events.md)
   -  [ ] implement `postStop`according to [lifecycle_events.md](https://github.com/openshift/odo/blob/master/docs/proposals/lifecycle_events.md)

- [x] It should replace the existing `devInit` command mechanism based on the devfile 1.0 specification.

## Links 
- Related issue: https://github.com/che-incubator/devworkspace-api/issues/32

/kind user-story
/area devfile

**Comment by kadel** [comment]
/status blocked
#2918 we need devfile v2 parser first

**Comment by upLukeWeston** [comment]
After discussing potential solutions (with @johnmcollier, @elsony, @EnriqueL8) we came to an agreement for the time being on how each of the lifecycle bindings could be used and what would trigger them. 

Proposed event timeline:
- Pre Start  (in initContainer) e.g:
    - Component Starts (Pod)
    - Containers Creating 
- devinit becomes PostStart E.g Parent Pom/maven install
- Build and Run commands
- Odo delete component triggers these both events:
    - PreStop before killing the component
    - PostStop after the pod/component killed: e.g Cleanup work

There are still some unanswered questions regarding differentiating commands between multiple projects within the same devfile, and the applicability of lifecycle bindings because of their intended functionalities being Workspace specific in Che.
Ongoing discussions and more details can be found on [this google doc](https://docs.google.com/document/d/1Xw8CDaGJXincggtObOeeYrgr-LrHRkWKknY-VUeXyDk/edit?usp=sharing).

**Comment by kadel** [comment]
I'm afraid that it might be too early to start implementing this.
I can still see a lot of unanswered questions.

Like is `preStart` going to be implemented as an InitContainer?
Are the rest of the commands be just executed similarly to how the "build" is done?
What will happen when some of the commands fail?
When will the `preStop` and `postStop` commands execute? How will odo know when they need to be executed?

**Comment by neeraj-laad** [comment]
I thought this issue was only for migrating the container initialisation step (`devInit`) with devfile v2. How we leverage other events can be discussed independently?

We should still have clarity on how we handle failures though.

**Comment by elsony** [comment]
+1 for having the complete design before implementing. We can stage in the implementation but the complete design should be before staging in the implementation.

**Comment by gorkem** [comment]
Is this really blocked? It has the blocked label.

**Comment by upLukeWeston** [comment]
No, I believe it was initially blocked by the Devfile v2 Parser.

**Comment by elsony** [comment]
Removing the block since we have the v2 parser already.

**Comment by maysunfaisal** [comment]
FYI there is a dup issue here for the remaining https://github.com/openshift/odo/issues/3569

**Comment by kadel** [comment]
`postStart` was implemented and merged in https://github.com/openshift/odo/pull/3533

Separate user story was opened for the rest of the events (`preStart`, `preStop` and`postStop`) https://github.com/openshift/odo/issues/3569

/close
