### ISSUE TITLE
"odo config set" doesn't validate port values and thus "odo describe" panics

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3036]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
https://github.com/openshift/odo/pull/3008#discussion_r416561531
```sh
$ odo config set ports 909,808 -f
 ✓  Local config successfully updated

Run `odo push --config` command to apply changes to the cluster

$ odo describe 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/openshift/odo/pkg/component.getPortsProtocolMapping(0xc0006136c0, 0x2, 0x2, 0x0)
        /home/mrinaldas/go/src/github.com/openshift/odo/pkg/component/component.go:991 +0x177
github.com/openshift/odo/pkg/component.GetComponentFromConfig(0xc000ba7500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mrinaldas/go/src/github.com/openshift/odo/pkg/component/component.go:962 +0x6d6
github.
```

## Actual behavior
`odo describe` panics because `odo config set` doesn't perform a check for ports provided by the user

## Expected behavior
odo should validate that provided value for ports follow `<port>/<protocol>` format and the values are valid.

**Comment by dev-gaur** [comment]
I tried reproducing this issue but could not. 
After a discussion with @dharmit , I found out that this has been partially fixed by #3224 and the rest of the problem that still persists is depicted in #3229.

Nevertheless, I feel that there should be proper validation for config parameters provided by user via `odo config set param value` command, which is currently absent right now : https://github.com/openshift/odo/blob/master/pkg/odo/cli/config/set.go#L62 .

Therefore, to add validations, I've created #3259 .
