### ISSUE TITLE
odo create fails even though project URL is accessible

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#3073]
/kind bug

## What versions of software are you using?

**Operating System:**
Mac OS

**Output of `odo version`:**
odo v1.2.0 (7f14dab08)

Server: https://c101-e.us-east.containers.cloud.ibm.com:30409
Kubernetes: v1.16.2

## How did you run odo exactly?
```
odo preference set experimental true
odo create openLiberty myapp --downloadSource
```

## Actual behavior
This worked fine in several different folders over the past week, then one time I opened up my laptop and tried again:
```
Experimental mode is enabled, use at your own risk
 ✗ Get https://raw.githubusercontent.com/elsony/devfile-registry/master/devfiles/index.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
I confirmed that I could curl the URL above and open it via browser, so it wasn't an access problem. I tried reinstalling odo and deleting the preferences and it was still failing. Finally, in desperation @johnmcollier suggested switching to a different IP. I tethered to my phone and was able to run the command. I switching back and it still worked. I don't have a clue what's going on here, but seems like something cached in network layer even across command invocations?

## Expected behavior
odo create would work as normal.

## Any logs, error output, etc?
John suggested I try running with -v4 option while it was failing, it didn't provide any additional hints:

```
I0504 10:05:26.387874  68772 preference.go:165] The path for preference file is /Users/deboer/.odo/preference.yaml
Experimental mode is enabled, use at your own risk
I0504 10:05:26.388834  68772 util.go:396] path ./.odo/config.yaml doesn't exist, skipping it
I0504 10:05:26.388849  68772 preference.go:165] The path for preference file is /Users/deboer/.odo/preference.yaml
 ✗ Get https://raw.githubusercontent.com/elsony/devfile-registry/master/devfiles/index.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by johnmcollier** [comment]
@gmarcy also hit this today.

Okay, so reading over https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/ helped clarify some things. It looks like we need to set `ResponseHeaderTimeout` in our code.

**Comment by johnmcollier** [comment]
I've got a PR up at #3119

/assign

**Comment by GeekArthur** [comment]
This is interesting issue and I don't think odo V style logging (`-v 4`) can give us more detailed information as the error is from golang `net/http` package and odo is just wrapper of that package (If the error is from odo V style logging is useful). Check the `net/http` source code here https://github.com/golang/go/blob/master/src/net/http/client.go#L724 can double confirm there is no more specific error we can get from `net/http` error handling.

I am not sure set `ResponseHeaderTimeout` can actually resolve the issue given we already set 10 overall timeout here https://github.com/openshift/odo/blob/master/pkg/util/util.go#L683, although the 10 overall timeout covers the whole http request/response operations such as dial, handshake, process request header + body etc, I still think 10s overall timeout should sufficient for a simple index.json request from GitHub.

I think to debug this we can:
- Run `GODEBUG=http2debug=2 <odo command>` to investigate the actual network trace and see where exactly the error come from
- If curl works we can use `curl -v https://raw.githubusercontent.com/elsony/devfile-registry/master/devfiles/index.json` to see the return values of the _header_ to see if we can find something there, the reason is I notice we have two default registries
```
NAME                       URL
CheDevfileRegistry         https://che-devfile-registry.openshift.io
DefaultDevfileRegistry     https://raw.githubusercontent.com/elsony/devfile-registry/master
```
But seems like we _only_ hit the issue on `DefaultDevfileRegistry`, which makes me think that might or might not related with the registry

**Comment by johnmcollier** [comment]
@GeekArthur, I'll be honest and say I don't fully understand why this change worked, but it's the only thing that fixed the issue

**Comment by GeekArthur** [comment]
> @GeekArthur, I'll be honest and say I don't fully understand why this change worked, but it's the only thing that fixed the issue.
> 
> We were finding that the error was returning well before the 10 second timeout, so I suspect actually setting the timeout to some value allowed odo enough time to retrieve the headers and continue the request.

Agree, just read your PR description, looks like the changes worked on the environment that could consistently reproduce this issue, I think we all good if that's the case.
