### ISSUE TITLE
--downloadSource doesn't feel natural

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#3107]
/kind bug

## What versions of software are you using?

**Output of `odo version`:**
odo v1.2.0 (7f14dab)

Server: https://c101-e.us-east.containers.cloud.ibm.com:30409
Kubernetes: v1.16.2

## How did you run odo exactly?
```
odo preference set experimental true
odo create openLiberty myapp --downloadSource
```

## Expected behavior
After using odo for a few days, --downloadSource was the one option that I thought was a bit odd and didn't really fit. Yes, it _is_ downloading source, but it's already downloading the devfile without this option, and as a user I'm thinking about the function (creating a starter or default project) more than how it's happening and the fact it implies files being downloaded.

Suggest we change the option to something like "--starter".

**Comment by johnmcollier** [comment]
+1 for starter, I like that it's one word, it's concise and simple.

Other optional alternatives (that I'm less crazy about):
- `--starterProject`
- `--templateProject`
- `--downloadProject`

**Comment by GeekArthur** [comment]
Personally I like the following options that don't mention the word _Project_ 
1. `--starter`
2. `--templateSource`

Because IMO _Porject_ is pretty confused terminology (OpenShift project -> "namespace" VS devfile project -> template) and we should be careful to use it especially all OpenShift user might still think _Porject_ is _Namespace_ related thing by default

**Comment by neeraj-laad** [comment]
+1 for `--starter`

It is simple and conveys the operation/function the user is performing.

**Comment by EnriqueL8** [comment]
I think `--starter` is nice and simple, but we need to look at the semantic meaning of projects in a devfile. Are they really considered a starter project? Or all the components of my application?

**Comment by deboer-tim** [comment]
That's still being discussed (https://github.com/devfile/kubernetes-api/issues/42), but based on where it's at I think there will be a distinction between projects (part of the app, always cloned) and starters (optional resources to start with, copied in).

**Comment by sam-github** [comment]
I like `--starter`, I found --downloadSource undiscoverable (I didn't guess its purpose even from the CLI help). Later, perhaps, `--starter[=NAME | git-repo]` if people want to select a specific starter, though starters should have as little code as possible, so maybe a well run stack will not have many of them

**Comment by elsony** [comment]
1. +1 for --starter. In the odo case, we'll probably only use starters (optional sample app) and we'll probably never use projects which ties to the setup of a given workspace to always clone the project(s).
2. Following the pattern for https://github.com/openshift/odo/issues/3000, `--starter[=NAME]` will allow user to specify a specific starter within a devfile.  
3. If none specified by just using `--starter`, the first starter on the devfile will be used.
4. However, I don't think 'git-repo' fit into that command since the git repo info should be part of the starter definition in the devfile.

**Comment by elsony** [comment]
As specified in the odo terminology change proposal (https://docs.google.com/document/d/1PBZqactXlfSpeSwt7EkaVlnt43qsUV2eExwFXpYJahc/edit#heading=h.1y4eznz1mtnr), we'll rename the current `--downloadSource` option to `--starter`

**Comment by elsony** [comment]
This item should covers:
1. rename of the `--starter` in CLI
2. any required test change
3. doc changes

**Comment by johnmcollier** [comment]
I can work on this

/assign
