### ISSUE TITLE
odo push without .odo directory

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3144]
/kind user-story

## User Story
As a user I want to run start my application right after I clone the repo without running `odo create first` (`git clone https://.... && odo push`)

## Acceptance Criteria 
as described https://github.com/openshift/odo/issues/2822#issuecomment-624584047
- [ ] `odo push`  should use env.yaml file if it is available 
- [ ]  if `env.yaml` doesn't exist when `odo push` is executed, should create the env.yaml before it starts doing any cluster operations. 
- [ ] `env.yaml` should be populated with the default values (similar to `odo create <componentType>` without additional flags does). This means that it should record the current namespace as in KUBECONFIG and component name in `env.yaml`. The component name will be generated by the same rules as they are for  `odo create`.

## Links 
- Related issue: https://github.com/openshift/odo/issues/2822

/kind user-story
/priority high
/area devfile
/area devfilev2
/area push
/priority high
/triage ready

**Comment by cdrage** [comment]
@girishramnani @kadel 

I've opened up this issue too with regards to implementing this, as we're also missing some essential data.

For starters, we don't provide a default `metadata.name` in Devfile if the user does not provide a name when creation: https://github.com/openshift/odo/issues/3212

Otherwise, the implementation is quite straight-forward

**Comment by johnmcollier** [comment]
How about this order for determining the component name?
1) If the user specifies a name, use that as the component name
2) If no name specified, use metadata.Name if it’s there
3) Otherwise, fall back on the folder name?

If we decide to use that, we should update odo create as well to use the same flow (1->2->3)
