### ISSUE TITLE
`odo create <component-name> --registry` falls back to S2I component, if invalid registry used

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3167]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:master

## How did you run odo exactly?
```
$ odo create maven --registry blbla
Experimental mode is enabled, use at your own risk

 ⚠  Registry blbla is not set up properly with error: Unable to unmarshal the devfile index.json from https://raw.githubusercontent.com/blbla/devfiles/index.json: invalid character ':' after top-level value
Validation
 ✗  Checking devfile compatibility [102517ns]
 ✗  Creating a devfile component from registry: blbla [141367ns]

Please run `odo catalog list components` for a list of supported devfile component types
 ✗  imagestreams.image.openshift.io "maven" not found
```

## Actual behavior
mentioned above

## Expected behavior: odo should exits, as soon as an invalid registry is specified via flag, It is should not go ahead for further validation
```
$ odo create maven --registry blbla
Experimental mode is enabled, use at your own risk

 x Registry blbla is not set up properly with error: Unable to unmarshal the devfile index.json from https://raw.githubusercontent.com/blbla/devfiles/index.json: invalid character ':' after top-level value
Validation

```

**Comment by GeekArthur** [comment]
+1, we should handle the invalid registry error properly, basically better error handling would be:
1. If registry doesn't exist (eg. pass in fake registry) -> directly throw error to user and won't continue to run both devfile and s2i code (given currently s2i doesn't have registry support)
2. If registry exists but component type doesn't exist under the specified registry -> throw properly error to let user know the component type doesn't exist instead of using `Checking devfile compatibility` as that error may make users confused (users may think root cause is devfile doesn't exist under the specified registry OR root cause is devfile format/content is wrong)

Regarding another topic which is fully support s2i registry, that will be done under this issue: https://github.com/openshift/odo/issues/3156

**Comment by GeekArthur** [comment]
> If registry doesn't exist (eg. pass in fake registry) -> directly throw error to user and won't continue to run both devfile and s2i code (given currently s2i doesn't have registry support)

Add validation code to validate `--registry` value, the validation code should create a function/code block to get available registries from preference file then compare with the `--registry` value to validate registry existence and correctness

> If registry exists but component type doesn't exist under the specified registry -> throw another properly error to let user know the component type doesn't exist before throwing Checking devfile compatibility as only uses that error may make users confused (users may think root cause is devfile doesn't exist under the specified registry OR root cause is devfile format/content is wrong)

Give we have the code block
```
		for _, devfileComponent := range catalogDevfileList.Items {
			if co.devfileMetadata.componentType == devfileComponent.Name && devfileComponent.Support {
				co.devfileMetadata.devfileSupport = true
				co.devfileMetadata.devfileLink = devfileComponent.Link
				co.devfileMetadata.devfileRegistry = devfileComponent.Registry
			}
		}
```
`devfileComponent.Name` can be used for component type existence check
`devfileComponent.Support` can be used for component type compatibility check
