### ISSUE TITLE
"odo registry list" should not print an empty list when no registries are configured

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3268]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `master`

## How did you run odo exactly?
`odo registry list`

## Actual behavior
```sh
$ odo registry list
NAME     URL
```
## Expected behavior
Below message is just a suggestion.
```sh
$ odo registry list
 ✗  No devfile registries added to the configuration. Refer `odo registry add -h` to add one.
```

**Comment by GeekArthur** [comment]
I don't think we should error out for empty registry list, essentially empty registry list is not an error and having registry is also not mandatory. Listing registry it's just for displaying the current registry list to let user know which registry odo already connects to, if no registry is listed user still can create component from existing devfile with `--devfile` flag. The idea is same as `docker image ls` and `kubectl get <k8s resource>`, they just print an empty list instead of throwing error.

**Comment by johnmcollier** [comment]
Whether or not we should return an error, I don't think we should be displaying an empty list here. A message like @dharmit suggested would be good, `No devfile registries added to the configuration. Refer `odo registry add -h` to add one.`

This is in line with kubectl as well:
```
Johns-MacBook-Pro-3:~ johncollier$ kubectl get pods -n test
No resources found in test namespace.
```

**Comment by GeekArthur** [comment]
I thought `kubectl` and `docker` aligns with each other before, but obviously there are not.

This is what `docker` uses to list empty list
```
docker container ls                                                                                                                                                           
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
Similar output for `docker image ls`, but since @johnmcollier points out the `kubectl`, I am fine aligns with that.

**Comment by elsony** [comment]
Instead of trying to make it consistent with `kubectl` or `docker` (as they don't line up anyways). We should try to make it consistent across the board for commands within odo.  I think the suggested message on the original description is good since it:
1. notify that there is no registry available
2. suggest how to add one
I think this general pattern when returning an empty list is good (whether it is considered as an error is debatable, but I am fine with either).  

Regarding to our point of consistency, we should probably use the same pattern when doing other list command, e.g. in url list:
```
eyuentp2:odo-run-sampleproj eyuen$ odo url list
 ✗  no URLs found for component eyliberty1
```
If we follow the same pattern, the url list message should also suggest how to add one as part of the message to guide the user.

**Comment by dharmit** [comment]
> Instead of trying to make it consistent with kubectl or docker (as they don't line up anyways). We should try to make it consistent across the board for commands within odo. 

Exactly this. Consistency across the board for odo. :+1: 

> If we follow the same pattern, the url list message should also suggest how to add one as part of the message to guide the user.

Indeed. There will be two schools of thoughts here, I guess. One that recommends suggesting how to add a URL, registry, etc. when there's none found. Another that advocates referring documentation or `odo <command> -h`. 

As I mentioned in the issue description, `Expected behaviour` was a suggestion. We could discuss/vote these two different approaches I mentioned in the above paragraph in a separate issue, and to fix the current issue we could print `✗  No devfile registries added to the configuration.` or a similar message.
