### ISSUE TITLE
`odo create --downloadSource` is broken on Windows

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3296]
/kind bug
/area devfile
/area devfileV2

## What versions of software are you using?

**Operating System:**
Windows 10

It seems that `odo create --downloadSource` functions differently on Windows, as it doesn't clone the sample project to the same directory as the devfile, but rather a subdirectory within the folder:
```
PS D:\ododev\sourcemapping> odo create nodejs --downloadSource
Experimental mode is enabled, use at your own risk
Validation
 V  Checking devfile compatibility [979000ns]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [1ms]
 V  Validating devfile component [0ns]
Please use `odo push` command to create the component with source deployed
PS D:\ododev\sourcemapping> ls
    Directory: D:\ododev\sourcemapping
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2020-06-03   1:40 PM                .odo
d-----        2020-06-03   1:40 PM                odo-devfiles-nodejs-ex-39b5ec7
-a----        2020-06-03   1:40 PM            731 devfile.yaml
```
This will cause the source code to get synced to `/projects/<project-name>/odo-devfiles-nodejs-ex-39b5ec7`, rather than `/projects/<project-name>`, which breaks most of the devfiles in odo.

On macOS, it clones the sample project to the same directory as the devfile and everything works fine:
```
Johns-MacBook-Pro-3:nodejs johncollier$ odo create nodejs --downloadSource
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [100451ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [84496ns]
 ✓  Validating devfile component [177559ns]

Please use `odo push` command to create the component with source deployed
Johns-MacBook-Pro-3:nodejs johncollier$ ls
LICENSE			app			package-lock.json
README.md		devfile.yaml		package.json
```

**Comment by jgwest** [comment]
I'm able to reproduce on Windows as well (and not on Linux)... I `git bisect`ed the problem and it appears to be caused by this commit:
```
C:\Users\JONATHANWest\go\src\github.com\openshift\odo>git bisect good
34c757ed5eba9c46543136d54ec88b9a6507d29a is the first bad commit
commit 34c757ed5eba9c46543136d54ec88b9a6507d29a
Author: CameronMcWilliam <Cameron.McWilliam@ibm.com>
Date:   Wed May 27 23:39:32 2020 +0100
    Adding sparseCheckoutDir functionality to devfiles (#3042)
(...)
```

https://github.com/openshift/odo/pull/3042

**Comment by BarDweller** [comment]
I think this is due to.. 

https://github.com/openshift/odo/blob/4d69aab92593a148cf952ecaa0a1556ef43100fc/pkg/util/util.go#L903-L908

The code here is assuming that paths in zips are using platform local separators, which although _possible_ is a LOT less likely than them using forward slash (`/`) separators at all times. Apparently the zip spec itself requires this, but sadly it seems references to "Application Note 970311" that would be real handy to quote here, are mostly/entirely dead (even the java.util.zip java doc is referencing a link that no longer responds). In any case, the zips supplied via git are using forward slash, and they would be the important ones for this issue.

If I flip that line 904 `index := strings.Index(f.Name, string(os.PathSeparator))` to read `index := strings.Index(f.Name, "/")` that does appear to fix the bad path prefixed to the root of all extracts on Windows. (Oddly enough this is exactly what the function used to do, before the change for sparseCheckoutDir was added). 

However, this doesn't help the sparseCheckoutDir logic to function, as `filepath` is subsequently treated as if it were only using local separators, with future comparisons & processing repeatedly using `string(os.PathSeparator)`

To resolve that, I added a quick call to perform `filename = filepath.FromSlash(filename)` immediately before the `match,err := filepath.Match(pathToUnzip, filename)` .. which flips the zip entry path to be expressed using local separators, and that seems to be enough to allow the remaining logic to proceed as planned. 

While you're in the area... the block 

https://github.com/openshift/odo/blob/4d69aab92593a148cf952ecaa0a1556ef43100fc/pkg/util/util.go#L916-L920

can be extracted to execute before the loop, as it's only modifying `pathToUnzip` which is initialized outside the for loop. 

I haven't looked further to see if there are expectations on the path format for the filenames array returned from Unzip, the path in question here only uses the return to see if there were more than zero files extracted, not looking at the format. There may be other paths invoking Unzip that care further.
