### ISSUE TITLE
pin down the version of gosec and wwhrd on CI scripts

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3359]
I want to resolve the underlying problem of this and this is the auto upgrading versions of gosec and wwhrd.
opening an issue to track and resolving that ASAP as well

_Originally posted by @girishramnani in https://github.com/openshift/odo/pull/3358#issuecomment-644639477_

**Comment by amitkrout** [comment]
```
$ go get github.com/onsi/ginkgo@1.12.0
go: cannot use path@version syntax in GOPATH mode
```
It does not work because odo does not use go mod package management.

However the new feature in go version 1.4.* can fetch the specific tag version like ```go get github.com/onsi/ginkgo@<tag>``` but our CI environment comprises go version 1.13.*. I have raised a concern via https://github.com/onsi/ginkgo/issues/707 to know how ginkgo binary is built and published.

**Comment by prietyc123** [comment]
@amitkrout Did you looked into https://github.com/onsi/ginkgo/issues/707#issuecomment-665179337 if it works for us.

**Comment by girishramnani** [comment]
it seems this was already done when we moved to gomod 
https://github.com/openshift/odo/blob/9200a7f99c2627c64d8ea2145aecf3ea2868d244/Makefile#L101
