### ISSUE TITLE
`odo app` support for devfile components

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3402]
/kind user-story

## User Story
As a user, I want to group different devfile components to an `app` similar to what I can do for s2i components.

## Background
odo has the `odo app` command for grouping existing s2i components under an app. 

## Acceptance Criteria 
- [x] It should behave the same as the existing `odo app` command but allowing devfile components to be added to the app
- [x] It should support `--app appname` parameter on `odo create` command for devfile components

We need to figure out where we store the app-component relationship data.

/kind user-story
/area devfile

**Comment by jgwest** [comment]
## Goals

The goal of this issue is to implement the `odo app *`/`odo list` commands, for devfiles, in such as way as to reproduce the existing non-dev-file/s2i behaviour of these commands.

A non-goal of this issue is to implement [app-level linking of components](https://github.com/openshift/odo/issues/2920). However, the work done as part of THIS issue should not prevent implementation of app-level linking of components in the future. A description of our initial thoughts on [app-level linking can be found here](https://docs.google.com/document/d/1PBZqactXlfSpeSwt7EkaVlnt43qsUV2eExwFXpYJahc).

## Implementation

The implementation for devfiles will thus work the same way as it does for s2i:
- All components will, by default, belong to an application named 'app'
- Deployments in a namespace on cluster will have the label `app.kubernetes.io/part-of=(name of odo app)` to indicate which app they are a part of
- The `env.yaml` for the component will contain a new 'Application' entry:
```
ComponentSettings:
  Application: (name of odo app)
```

## Specific behaviour of commands affected by this issue

- `odo list command`: query the cluster for components of the current application and print them (*)
- `odo app delete command`: delete k8s resources (of matching components) from the cluster, doesn't delete any local files (*)
- `odo app describe command`: describe components that match the application name, based on deployed k8s resources from the cluster (*)
- `odo app list command`: list applications found on the cluster, by scanning deployed k8s resources  (*)
- `odo component create`: Existing create behaviour, but now also sets the Application value in env.yaml
- `odo component push`: Existing push behaviour, but now applies the `app.kubernetes.io/part-of` label when pushing

(*) = uses 'app.kubernetes.io/part-of' to determine application of deployed k8s resources, eg don't use or check the component's env.yaml (in pwd/context) as part of the execution of this command; this is the same behaviour as S2I.


## Application-level component linking

In the near future (but not as part of this issue), we may add application-level awareness of component <-> component links.

To my mind there are at least a couple possible models:

1) Parent-child linking model: The application is the "parent" of the components, the application describes links between components, and the links between those components are stored in application metadata. Component metadata (either devfile.yaml/env.yaml) does not contain that link information. (This is the model described in the [google doc referenced above](https://docs.google.com/document/d/1PBZqactXlfSpeSwt7EkaVlnt43qsUV2eExwFXpYJahc).)

2) Peer-to-peer linking model: The components describe links to each other, and the role of the application is only to be a simple grouping of components.  Component metadata (devfile.yaml/env.yaml) DO contain link information.
    - This is closest to the existing S2I app model.

In either case, my expectation is that the behaviour of the `odo app *`/`odo app` command, as implemented in this issue, would be roughly the same, depending on which model of linking we go with, and thus I don't feel that the implementation details of this issue would prevent that future work.

**Comment by girishramnani** [comment]
@jgwest there is an overlap with https://github.com/openshift/odo/pull/3505

**Comment by jgwest** [comment]
I believe there is still overlap between this issue and https://github.com/openshift/odo/issues/3521

**Comment by prietyc123** [comment]
Removing `required-for-v2` label as v2.0.0 has been released.
