### ISSUE TITLE
Devfile v2: Registry listing is showing an invalid URL

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3485]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

See below, the URL is actually invalid:

```sh
▶ odo registry list
NAME                       URL
DefaultDevfileRegistry     https://raw.githubusercontent.com/odo-devfiles/registry/master
```

## Actual behavior

See above. Actual behaviour is an incorrect URL

## Expected behavior

The URL to be https://github.com/odo-devfiles/registry not the raw URL.

## Any logs, error output, etc?

N/A

**Comment by GeekArthur** [comment]
The design is that we divide the registry URL validation into two stages:
Early validation stage: Only validate registry URL basic format, happens when user adds registry URL
Validation stage: Validate registry URL accessibility, happens when user uses registry URL

That design is based on `yum-config-manager`, design proposal with details under this thread: https://github.com/openshift/odo/pull/2940#discussion_r417440866

Based on the design above, the registry URL `https://raw.githubusercontent.com/odo-devfiles/registry/master` is valid as we only validate the format instead of accessibility when adding URL. But the default registry URL will be changed to ` https://github.com/odo-devfiles/registry` in secure registry PR, so the issue you see will be resolved soon.

**Comment by kadel** [comment]
@GeekArthur 
This is completely unrelated to validation.

@cdrage
Devfile registry can by hosted using any httpd server. 

`https://raw.githubusercontent.com/odo-devfiles/registry/master ` is the correct devfile registry URL, this is where the registry is. The way how devfile registry works is that that there is an `index.json` on predefined  path (<registry url>/devfiles/idnex.json)

 `https://github.com/odo-devfiles/registry` is url to GitHub repository.

/triage invalid-bug
/close
