### ISSUE TITLE
Use feature flags instead of experimental mode

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#3599]
/kind feature

## Which functionality do you think we should add?
Experimental features should be activated based on a configuration file instead of hiding every experimental features under a single experimental flag.

## Why is this needed?
- Not all experimental features mature at the same speed making it difficult to manage all of them with a single flag
- Moving code out of the experimental state requires touching a lot of files while this would only require modifying a value in a single file if such features where managed by feature flags

**Comment by girishramnani** [comment]
we had this discussion a while back and the conclusion was that experimental mode is a good solution for us because 
- as all experimental mode features are under the same domain/wall (experimental), a developer gets to understand the impact their code is having on other experimental features giving them a headstart of resolving future integration problems.
- makes it error prone and confusing for early uses as they might forget to enable some feature flags so better to have a single flag i.e. experimental mode.
cc @kadel

**Comment by kadel** [comment]
> Not all experimental features mature at the same speed making it difficult to manage all of them with a single flag
> Moving code out of the experimental state requires touching a lot of files while this would only require modifying a value in a single file if such features where managed by feature flags

I completely agree with that. The current experimental mode was originally added only to include everything related to devfiles, and it was supposed to be removed once we fully move to devfile (in odo v2.0.0 release) But it got a little bit out of hand :-(

**Comment by kadel** [comment]
/close
There is no experimental feature in odo anymore. 
If we need something similar in the future we will go with the individual feature flags rather than one global experimental flag.
