### ISSUE TITLE
Remove --devfile parameter from non `odo create` commands.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3661]
/kind feature

## Which functionality do you think we should add?

See discussion: https://openshiftdo.slack.com/archives/CQK6HE78S/p1596118006155100

We have 4 locations where `--devfile` is used outside of `odo create`. `--devfile` should not be located on these commands:

- odo exec
- odo url delete
- odo debug port-forward
- odo debug info

## Why is this needed?

There is no need to pass in `--devfile` if the default name is always `devfile.yaml` in the working directory.

**Comment by GeekArthur** [comment]
Other than removing all the `--devfile` in all existing commands except `odo create`, we should also document or send internal notice to let folks know DON’T ADD `--devfile` to ANY NEW COMMANDS, for example the `--devfile` of `odo exec` is from this PR https://github.com/openshift/odo/pull/3083 which is 2 weeks ago. Otherwise we may in a loop where keep removing and keep adding the `--devfile`

Another case I can find is `--devfile` for `odo url delete`. The `-devfile` is added by this PR https://github.com/openshift/odo/pull/3139 which is merged after the `--devfile` cleanup for all commands we did before.
