### ISSUE TITLE
Add linked component/service information in odo describe for devfile component and operator services

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3734]
/kind user-story

## User Story
As a user I want to see the components and services linked to my current component So that I can verify that the secrets were added correctly.

## Acceptance Criteria 
- [ ] It should show the linked components information in the `odo describe` output
- [ ] It should show the linked services information in the `odo describe` output
- [ ] ~~should work with both catalog services and operator services~~

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

**Comment by girishramnani** [comment]
Blocked on https://github.com/openshift/odo/issues/3644

**Comment by kadel** [comment]
> Blocked on #3644

not bloked anymore
/remove blocked
/reopen

**Comment by feloy** [comment]
To display information on links, should odo rely on:
- only the deployed resources (like it is now)
- only the information on the devfile
- both?

For the moment, the display of links is based on the presence of a envFrom/secret in the component deployment (pkg/component/pushed_component.go), which (my bad) does not handle the links with the `--bind-as-files` option.

**Comment by dharmit** [comment]
I hadn't checked `odo describe` in some time, so when I saw this question, I started playing with `odo describe`, and it seemed to me to be hung on connection with cluster. Which led me to think that odo describe should reflect cluster status. Looking at `odo describe -h` didn't help me understand whether it's something that describes local+remote, remote only, or both states.

Simply put, I am confused about what `odo describe` should exactly do.

**Comment by kadel** [comment]
> Simply put, I am confused about what `odo describe` should exactly do.

It should display all information about the component that it can.
In case that the component is not pushed, the output will be limited, because we can't get all the information.

## the current state is:
### for unpushed
```
▶ odo describe
Component Name: java-maven-spring-petcl-ysce
Type: java-maven
Storage:
 · m2 of size 1Gi mounted to /home/user/.m2
URLs:
 · URL named http-8080 will be exposed via 8080

```

### for pushed

```
▶ odo describe
Component Name: java-maven-spring-petcl-ysce
Type: java-maven
Environment Variables:
 · PROJECTS_ROOT=/projects
 · PROJECT_SOURCE=/projects
 · DEBUG_PORT=5858
Storage:
 · m2 of size 1Gi mounted to /home/user/.m2
URLs:
 · http://http-8080-java-maven-spring-petcl-ysce-test.apps-crc.testing exposed via 8080
```

### after creating a link to service `odo link Database/postgresql `

### unpushed link
but once implemented it could look like this
```
▶ odo describe
Component Name: java-maven-spring-petcl-hwus
Type: java-maven
Environment Variables:
 · PROJECTS_ROOT=/projects
 · PROJECT_SOURCE=/projects
 · DEBUG_PORT=5858
Storage:
 · m2 of size 1Gi mounted to /home/user/.m2
URLs:
 · http://http-8080-java-maven-spring-petcl-hwus-test.apps-crc.testing exposed via 8080
```
(missing link info)

### pushed  link
```
▶ odo describe
Component Name: java-maven-spring-petcl-ysce
Type: java-maven
Environment Variables:
 · PROJECTS_ROOT=/projects
 · PROJECT_SOURCE=/projects
 · DEBUG_PORT=5858
Storage:
 · m2 of size 1Gi mounted to /home/user/.m2
URLs:
 · http://http-8080-java-maven-spring-petcl-ysce-test.apps-crc.testing exposed via 8080
Linked Services:
 · java-maven-spring-petcl-ysce-database-postgresql-6997536c
   Environment Variables:
    · DATABASE_CLUSTERIP
```

## Changes


### unpushed link
```
▶ odo describe
Component Name: java-maven-spring-petcl-ysce
Type: java-maven
Environment Variables:
 · PROJECTS_ROOT=/projects
 · PROJECT_SOURCE=/projects
 · DEBUG_PORT=5858
Storage:
 · m2 of size 1Gi mounted to /home/user/.m2
URLs:
 · http://http-8080-java-maven-spring-petcl-ysce-test.apps-crc.testing exposed via 8080
Linked Services:
 · Database/postgresql 
```
There is information about the name of the linked Service, but not info about env variables because they can be determined only after SB creation. The name of the `Linked Service` can be extracted from SB saved in devfile.yaml


### pushed link
```
▶ odo describe
Component Name: java-maven-spring-petcl-ysce
Type: java-maven
Environment Variables:
 · PROJECTS_ROOT=/projects
 · PROJECT_SOURCE=/projects
 · DEBUG_PORT=5858
Storage:
 · m2 of size 1Gi mounted to /home/user/.m2
URLs:
 · http://http-8080-java-maven-spring-petcl-ysce-test.apps-crc.testing exposed via 8080
Linked Services:
 · Database/postgresql
   Environment Variables:
    · DATABASE_CLUSTERIP
```
Notice change in `Linked Services` name.  It looks like currently, It shows the ServiceBinding name, but that is something that is hidden from the user. User wants to know the name of the service so instead of `java-maven-spring-petcl-ysce-database-postgresql-6997536c` it should show  `Database/postgresql`. This can be extracted from SB `services`  section. 




in case of `--bind-as-file`  it could be something like this:
```
Linked Services:
 · Database/postgresql
   Files:
    · /bindings/database_clusterip
```


If link is made to another component (Deployment) it could look like this:
```
Linked Services:
 · Deployment/backend-users
   Environment Variables:
    · SERVICE_BACKEND_IP
 · Deployment/backend-warehouse
   Files:
    · /bindings/warehouse_clusterip
```
