### ISSUE TITLE
Clean up error wrapping 

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3911]
- Looks like with moving up the go version, error wrapping functionality has changed a bit. For example, you can't return `errors.Wrap(err, "unable to parse devfile")` from odo. It has to be `fmt.Errorf("unable to parse the devfile %s, with error: %s", o.DevfilePath, err)`. Otherwise you may lose all the error context wrapping from the child funcs.

- I have also noticed that sometimes we have way too much wrapping. Is the following error wrapping really necessary?

```
Maysuns-MacBook-Pro:nodejs-ex maysun$ odo push

Validation
 ✗  Validating the devfile [358336ns]
 ✗  Failed to start component with name mjfnode. Error: Failed to create the component: failed to validate devfile build and run commands: 
there should be exactly one default command for command group build, currently there is more than one default command
```

- I have also noticed that the error wrapping has diff messages for the same func call across the odo code, we should stay consistent with the messaging. Its best to have an error.go file with all the custom errors so that error msgs are consistent across the board :) For example, https://github.com/openshift/odo/blob/master/pkg/devfile/validate/errors.go

/kind cleanup
/area devfile

**Comment by johnmcollier** [comment]
FWIW, I posted a similar message on slack here: https://openshiftdo.slack.com/archives/CQK6HE78S/p1599268565141800, as did Jingfu https://openshiftdo.slack.com/archives/CQK6HE78S/p1588964792403000. A lot of our error wrapping is being ignored because `util.LogErrorAndExit` only returns the cause of the error, rather than the error itself.

So from some past conversations, we _do_ want to limit the amount of error wrapping that we do, to avoid monoliths like the one that you posted (or even bigger error messages), but there are cases where it is useful still.

+1 on doing a general clean up of our error wrapping, most of it's not being printed at all, and I think a lot isn't even necessary. For the error wrapping that we determine useful, we should convert to use `fmt.Errorf` instead.

**Comment by maysunfaisal** [comment]
looks like we both encountered it while working with devfile parsing

**Comment by adisky** [comment]
agreed with both the concerns, at some places it is redundant and at some places nothing, logged similar kind of issue long back 
https://github.com/openshift/odo/issues/2709

**Comment by elsony** [comment]
Given the scope of the change, this item is going to be a post v2 GA item to avoid introducing potential instability to the GA code.
