### ISSUE TITLE
postStart event not honored when subsequent odo push invoke causes a new pod to start

### ISSUE THREAD

**Issue by ajm01** [openshift/odo#4017]
/kind bug

## What versions of software are you using?

**Operating System:**
Windows

**Output of `odo version`:**
```$ odo version
odo v2.0.0-beta-1 (c19e1f390)
Server: https://api.slobbed.os.fyre.ibm.com:6443
Kubernetes: v1.16.2
```

## Actual behavior
I have a postStart event/command defined in my devfile that copies files from the base image to a certain location in the working dir ... When I do the first initial odo push, I see it get invoked and the copy happens as expected.
If I do a second push, but supply an alternative run command (--run-command <some other command>), the current pod gets destroyed and a new pod starts (because of the new run command supplied I am guessing) - but the postStart event is not honored...does not get invoked in the new pod/container and the copy i expect does not occur.

## Expected behavior
On the second (or subsequent) odo push containing a --run-command arg, I would expect the postStart event to be honored in the new pod that is started.

**Comment by adisky** [comment]
I am able to reproduce it, pod gets recreated when we update run command as we are inserting it as env variable `ODO_COMMAND_RUN`, we need to execute the `postStart` event in this case.

**Comment by scottkurz** [comment]
Also noticing if I just delete my 'run' pod then k8s will start a new one based on the deployment without re-executing the `postStart` event. 

While that aligns with the doc: https://odo.dev/file-reference/#event-object
> PostStart events are executed when the Kubernetes deployment for the odo component is created. 

I'm surprised that the event isn't executed each time the 'run' container is started.    Otherwise, the first pod isn't going to be identical to later pods, which seems surprising to me.

**Comment by adisky** [comment]
> Also noticing if I just delete my 'run' pod then k8s will start a new one based on the deployment without re-executing the `postStart` event.

It is not something we should handle, component created with odo should be modified/updated via odo.
If you directly delete a pod via kuberenetes, odo does not know about its recreation, it won't be able to execute any commands, events

**Comment by scottkurz** [comment]
> It is not something we should handle, component created with odo should be modified/updated via odo.

Interesting.   I'm not saying there is a compelling use case, just wondering.   Also, one could use a "preStart" cmd with the case I mentioned, since that will create an init container which would be executed with a new k8s-created pod.

**Comment by maysunfaisal** [comment]
`postStart` logic needs to be updated. This is something that had been discussed about earlier because Odo & Che understanding of the devfile was a bit different due to how they function - Che is workspace based UX and Odo is container based UX. 

See discussion and agreement with @kadel here -> https://github.com/devfile/api/issues/105#issuecomment-674895424

**Comment by adisky** [comment]
@maysunfaisal Thanks for sharing the discussion link

I think, the way odo is using `postStart` event to initialize something and save the outcomes of initialization. e.g. downloading some dependency, populating a cache, like in quarkus devfile `postStart` event is `mvn compile` and we want run it just once not even with further odo push.

The problem here is we are not saving the `postStart` data anywhere as we are using `emptyDir`, It would get resolved once we start using `pvc`. 

however agreed, the expectations and definitions of `postStart` needs to be discussed.

**Comment by maysunfaisal** [comment]
@adisky Just checked, Odo executes postStart only after a source sync.

**Comment by adisky** [comment]
> @adisky Just checked, Odo executes postStart only after a source sync.

saying the same, currently source code is synced before `postStart` event, if we want to execute `postStart` event whenever a new pod gets created(pod eviction, pod deletion), we need to keep in mind source code should be synced before that.

**Comment by sarveshtamba** [comment]
Is this related to #3905 and #4030 ?

**Comment by kadel** [comment]
> `postStart` logic may need to be updated if this is something users dont agree with.. This is something that had been discussed about earlier because Odo & Che understanding of the devfile was a bit different due to how they function - Che is workspace based UX and Odo is container based UX.
> 
> See discussion and agreement with @kadel here -> [devfile/api#105 (comment)](https://github.com/devfile/api/issues/105#issuecomment-674895424)
> 
> @kadel, your thoughts?

Problem is that `preStart` behavior is still not clearly defined in Devfile spec. First, we need to come up with a clear definition on the Devfile side, and then we can update its implementation. 

Currently, postStart is defined as:

> Names of commands that should be executed after the workspace is completely started. In the case of Che-Theia, these commands should be executed after all plugins and extensions have started, including project cloning. This means that those commands are not triggered until the user opens the IDE in his browser.

If we clearly define that the `postStart` needs to be executed every time the Deployment is restarted that we can try to implement it, it won't be easy but  I have a few ideas on how we could do it.

But I think that the root cause of this particular issue is actually the fact that Deployments created by odo don't persist source code (emptyDir volume is used) if we would use PVC the files copied into working dir in `postStart` event would be still there even after the Pod gets restarted (due to user executing `odo push --run-command`)

**Comment by sarveshtamba** [comment]
@kadel any luck here?
