### ISSUE TITLE
odo installation on windows is broken

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#4062]
/kind bug

There are multiple issues with windows installation. 
1. There are 2 distributions for windows one _.exe_ and _.tar.gz_ unfortunately windows does not come with tools to handle _tar.gz_ by default. We should produce .zip files for windows like we do for crc. 

2. I think there is a mismatch with the [instructions](https://odo.dev/docs/installing-odo/#installing-odo-on-windows) and the filenames.  Instructions refer to a `odo.exe` while linking to `odo-windows-amd64.exe`. There are no instructions to rename this file. 

3. Step 2 on the installation instructions refers to a `GOPATH` which is not something most windows users would have configured.

**Comment by rnapoles-rh** [comment]
Regarding item _1- ... we should produce .zip files for windows like we do for crc.,_ since we provide an executable file for download, it would be silly to provide a zip file as it adds an extra step for the user to unzip the executable. We will not provide a zip file. Unless anyone disagrees.

**Comment by gorkem** [comment]
We are already providing a `tar.gz` in addition to the `.exe` are you suggesting that we do not provide the `tar.gz` going forward?

**Comment by deboer-tim** [comment]
To be clear, the request was to produce a .zip instead of .tar.gz (i.e. just change the compression format), not a new/second file.

**Comment by mohammedzee1000** [comment]
Required changes:
 1. Update logic https://github.com/openshift/odo/blob/master/scripts/prepare-release.sh#L24-L41 to use gzip for windows and tar.gz otherwise
2. Update to copy .zip as well files https://github.com/openshift/odo/blob/master/rpms/openshift-odo.spec#L63
3. Update tar.gz to zip https://github.com/openshift/odo/blob/master/rpms/openshift-odo.spec#L95
4. Review test script https://github.com/openshift/odo/blob/master/scripts/rpm-x86_64-test.sh for changes
