### ISSUE TITLE
Use PSI for running the tests currently running on Travis

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4253]
Move the tests currently running on Travis to PSI cluster. These are mainly OpenShift 3.11 and Kubernetes tests.

- [x] Kubernetes tests on PSI #4287 
- [ ] OpenShift 3.x tests on PSI #4288 

/area testing
/assign @mohammedzee1000

**Comment by prietyc123** [comment]
> Move the tests currently running on Travis to PSI cluster. 

AFAIK PSI is already overloaded with the test execution running on ocp 4.* clusters with multiple platform and we are in need of more resources. IIRC we intentionally removed 3.11 cluster on PSI due to insufficiency of resources and moving travis to PSI will be even worse I think. IMO choosing PSI would be nice if we have ample of resources and that would definitely take some time. More importantly we can not escape running tests on kubernetes for long because it might lead to broken code as before. IMO using Github CI could be a best choice instead of PSI. Once we have ample of resources, we can think of moving it slowly. @kadel @mohammedzee1000 WDYT?

**Comment by dharmit** [comment]
Based on the discussion we had on stand-up call, I think we're good to use PSI hardware for these tests. We need to bring up minikube & minishift using containers instead of bringing them up as VMs. Breaking this down into two issues. Let's start by focussing on minikube since it boots fast and we really need to get k8s tests back ASAP.

**Comment by kadel** [comment]
> AFAIK PSI is already overloaded with the test execution running on ocp 4.* clusters with multiple platform and we are in need of more resources.

How do you know that the ocp 4.x cluser is overloaded? I'm using it almost every day, and haven't noticed any problems.
Do we have any metrics suggesting that it is getting overloaded?
on PSI we are using about 3/4 of resources, we still have a lot to spare

**Comment by dharmit** [comment]
/remove-lifecycle stale

@rnapoles-rh @prietyc123 please close this one when the issues related to it are done.

**Comment by prietyc123** [comment]
> OpenShift 3.x tests on PSI Use PSI for running OpenShift 3.x tests #4288

Not relevant anymore. As we don't support 3.11 now. Apart from this all the tests running on travis (windows and macOS unit test, kubernetes job) are successfully running on prs now. So closing this issue

/close
