### ISSUE TITLE
How to use other Devfiles which is hardcode on tests/examples/source/devfiles directory

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#4290]
/kind bug

## What versions of software are you using?

**Operating System:**
Rhel 8.2
**Output of `odo version`:**
odo v2.0.2 (bf6b1b4c3)
## How did you run odo exactly?
nightly CI

## Actual behavior
For integrating devfiles related integration and e2e tests on nightly CI for IBM Z&Power, we need to change the devfiles used in tests. One way is to use other secure devfiles registry on GitHub repo . But there are still some subset of tests are hardcoded with devfiles for x86 . Those devfiles are put on tests/examples/source/devfiles directory. 

## Expected behavior
one way to replace those devfiles on tests/examples/source/devfiles directory

**Comment by prietyc123** [comment]
@zhengxiaomei123 I have gone through the devfile examples and observed nodejs devfiles uses multi arch supported images https://github.com/openshift/odo/blob/master/tests/examples/source/devfiles/nodejs/devfile.yaml#L12 , So didn't find any difficulties there. However yes, there are some `quay.io` [java images](https://github.com/openshift/odo/blob/master/tests/examples/source/devfiles/springboot/devfile.yaml#L23) which is not available for Multi Arch support. So I have created one issue https://github.com/eclipse/che/issues/18610 (just keep an eye). Once it is done, I think you will be good to go.

> one way to replace those devfiles on tests/examples/source/devfiles directory
Apart from using multi arch supported images, we do have solution to create one devfile related library function to handle multi arch devfile issues where you can use your own defined devfiles supported on `s390x`. Instead of adding patches within the code, I would suggest to create a generic library function and use it across the test. Please let me know if you have any concern.

**Comment by sarveshtamba** [comment]
@prietyc123 we will need multi arch images for ppc64le too.

**Comment by zhengxiaomei123** [comment]
@prietyc123 Thanks. The generic library function sounds great. Do you have any examples to create a generic library function?

**Comment by prietyc123** [comment]
> Do you have any examples to create a generic library function

TBH, I don't find such examples in the helper file till now. But the idea is check the component, if it is java then use the devfiles according to the arch.

**Comment by dharmit** [comment]
@prietyc123 is there anything here that we can help with from our side? This can be fixed either by having the same images available on quay.io for multi arch or a function (or some extra code), right?

@zhengxiaomei123 thinking out loud here - for the function part, I think you can make use of `runtime.GOARCH` and make a decision based on that. And we can discuss if the code can remain in the odo repo itself.

**Comment by prietyc123** [comment]
> is there anything here that we can help with from our side? 

AFAIU, no.

> This can be fixed either by having the same images available on quay.io for multi arch or a function (or some extra code), right?

Yes, and I have created one issue on their repo https://github.com/eclipse/che/issues/18610
