### ISSUE TITLE
devfile validation fails if folder name is not valid

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#4305]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOs

**Output of `odo version`:**

odo 2.0.3

## How did you run odo exactly?

odo push

## Actual behavior
When I run odo push on a folder with devfile. devfile validation fails with the following. 
the _staticHTML_ is the name of the folder and I never set a component name. 
I think odo is setting the component name from folder name without converting it to be vaid.

```shell
❯ odo push

Validation
 ✗  Failed to start component with name staticHTML. Error: Failed to create the component: component name "staticHTML" is not valid, component name should conform the following requirements: 
- Contain at most 63 characters
- Contain only lowercase alphanumeric characters or ‘-’
- Start with an alphanumeric character
- End with an alphanumeric character
- Must not contain all numeric values
```

## Expected behavior
validation does not fail

**Comment by kadel** [comment]
> I think odo is setting the component name from folder name without converting it to be vaid.

Yes, that is what is happening here :-(

odo needs to convert the directory name into the always valid component name.
odo needs to do the following  cleanup before using value as a component name:
 1. convert to lowercase
 2. remove all non-alphanumeric characters except `-`
 4. if it is all numeric values, prepend it with `x`
 3. remove all leading and trailing non-alphanumeric characters (because of the previous step, this can be only `-`)

**Comment by girishramnani** [comment]
I can take a look at this
