### ISSUE TITLE
Move "GetComponentContext" to a util package

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4340]
* In `pkg/odo/cli/url`, we are calling this method which is in `pkg/odo/cli/component`. 
* `URLCreateOptions` and `PushOptions` are used interchangeably (as I can see, `GetComponentContext` is in the method set of `PushOptions` struct).
* Also, this function gets the value which can be used in other CLI packages as well.

It seems like this function belongs to some kind of util package, or other top level file for some component instead of being in `pkg/odo/cli/component/push.go`.

Besides that, should it be removed from the method set of `PushOptions` and put somewhere else? Some kind of common options that are common among various different options viz. `PushOptions`, `URLCreateOptions`, `ComponentOptions`, etc.

_Originally posted by @dharmit in https://github.com/openshift/odo/pull/4311#discussion_r549645173_

/kind discussion
/kind code-refactoring
/good-first-issue

**Comment by niconosenzo** [comment]
@dharmit If this is ok for you, I may have a look and discuss some ideas before submitting any change.

**Comment by dharmit** [comment]
@niconosenzo absolutely! Discussing before coding is always welcome! If you'd like to work on this, feel free to assign it to yourself.

**Comment by mik-dass** [comment]
> In pkg/odo/cli/url, we are calling this method which is in pkg/odo/cli/component.
URLCreateOptions and PushOptions are used interchangeably (as I can see, GetComponentContext is in the method set of PushOptions struct).

We are using the GetComponentContext() in other packages like cli for URL etc to trigger the push logic for the now flag in other packages. 

https://github.com/openshift/odo/blob/e7664393988c11683588232b50e944484fbea999/pkg/odo/cli/url/create.go#L189

> Besides that, should it be removed from the method set of PushOptions and put somewhere else?

The fix would be to design a way so that we can trigger Push() from the component package without requiring the dependency of the component CLI code https://github.com/openshift/odo/blob/e7664393988c11683588232b50e944484fbea999/pkg/odo/cli/url/create.go#L10 but that might need a lot of refactoring.
