### ISSUE TITLE
Enable periodic jobs for "latest+1"

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4503]
#4490 

/area testing

**Comment by prietyc123** [comment]
PR https://github.com/openshift/release/pull/16813 will fix this.

**Comment by prietyc123** [comment]
I will handle it in another pr because there are some failures observed while enabling 4.8 jobs https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16813/rehearse-16813-periodic-ci-openshift-odo-master-v4.8-integration-e2e-periodic/1371461371509608448#1:build-log.txt%3A1322 . It needs dedicated time of individual. So moving it to next sprint.
