### ISSUE TITLE
Doc verification for v2.2.0

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4645]
/kind user-story

## User Story
As a user I should not get any incorrect odo steps/flows in https://odo.dev/ and https://docs.openshift.com/container-platform/4.7/cli_reference/developer_cli_odo/understanding-odo.html

## Acceptance Criteria 
- [ ] https://odo.dev/ and https://docs.openshift.com/container-platform/4.7/cli_reference/developer_cli_odo/understanding-odo.html should not contain any incorrect or missing content

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by boczkowska** [comment]
@prietyc123 release Notes for downstream docs https://github.com/openshift/openshift-docs/pull/31737 PTAL and verify. 
The preview: https://deploy-preview-31737--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/developer_cli_odo/odo-release-notes.html 
This contains the changes for 2.1 and 2.2 releases combined since there were not separate docs for 2.1.

The Bugzilla issues (https://github.com/openshift/odo/issues/4644) are necessary so we can link them in as KIs in the RNs on the OpenShift portal (unfortunately, no GH links are allowed). For now, I've added GH links for some tentative Kis as WIP, I can file them as BZs once you confirm.

**Comment by dharmit** [comment]
Closing since we have 2.2 out.

/close
