### ISSUE TITLE
odo catalog list components fails with non existing kubeconfig

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4687]
```
▶ KUBECONFIG=/asdf odo catalog list components  
W0504 19:14:24.251928   26066 loader.go:223] Config not found: /asdf
 ✗  invalid configuration: no configuration has been provided
Please login to your server: 

odo login https://mycluster.mydomain.com
```

/kind bug
/priority medium

**Comment by girishramnani** [comment]
If I complete my tasks for the sprint, I would like to work on this issue

**Comment by mohammedzee1000** [comment]
Based on my research, i have found that, we initialize context in `list components` as below

https://github.com/openshift/odo/blob/17a078b67e9f6a2fed97b5bd5bab68c9505bf7cb/pkg/odo/cli/catalog/list/components.go#L46

This is basically the function below

https://github.com/openshift/odo/blob/17a078b67e9f6a2fed97b5bd5bab68c9505bf7cb/pkg/odo/genericclioptions/context.go#L160-L170

The call on the line 169 there, leads to function as below 

https://github.com/openshift/odo/blob/17a078b67e9f6a2fed97b5bd5bab68c9505bf7cb/pkg/odo/genericclioptions/context.go#L226-L270

The source of the problem is line 269

https://github.com/openshift/odo/blob/17a078b67e9f6a2fed97b5bd5bab68c9505bf7cb/pkg/odo/genericclioptions/context.go#L229-L232

**Comment by mohammedzee1000** [comment]
To fix this problem, I propose the following solution:

- [ ] Initialize `supported` variable to false
- [ ] Initialize Context and run `supported, err = o.Client.IsImageStreamSupported()` only if `KUBECONFIG` env is `""` or if specified path exists. This should prevent listing of image stream based components completely if `KUBECONFIG` is invalid path.
- [ ] Add tests to ensure it works as expected.
