### ISSUE TITLE
With devfile containing persistent storage component, failure on `odo push` after `odo link` trying to (re)create already-existing PVC

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#4917]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

odo v2.2.3 (4e2f6ddf1)
Kubernetes: v1.20.0+bafe72f

## How did you run odo exactly?

1. git clone git@github.com:mezarin/application-stack-samples.git; git checkout addGradleSupportToJPASample; cd jpa
2. curl -L https://raw.githubusercontent.com/OpenLiberty/application-stack-samples/main/devfiles/gradle-image/devfile.yaml -o devfile.yaml
3. odo create db2p
4. _<Follow instructions in https://odo.dev/docs/deploying-java-app-with-database to create db.yaml>_
5. odo service create --from-file db.yaml
6. odo push
7. odo link Database/database
8. odo push

Note there's a persistent component here:

```yaml
  - name: gradle
    volume:
      size: 3Gi
```

## Actual behavior

```
 Creating Kubernetes resources for component db2p
 I0715 18:52:25.534431   14296 preference.go:220] The path for preference file is C:\Users\ScottKurz\.odo\preference.yaml
 I0715 19:02:30.312058   14296 kubernetes.go:57] Creating a PVC with name gradle-db2p-app and labels map[app:app app.kubernetes.io/instance:db2p app.kubernetes.io/managed-by:odo app.kubernetes.io/managed-by-version:v2.2.3 app.kubernetes.io/part-of:app app.kubernetes.io/storage-name:gradle component:db2p storage-name:gradle]
  X  Failed to start component with name "db2p". Error: Failed to create the component: unable to create or update component: unable to create PVC: unable to create PVC: persistentvolumeclaims "gradle-db2p-app" already exists
```

Not only does the push return a failure, but also it seems that the file sync logic is aborted, and I end up with an empty `/projects` folder.     I wonder if a failure of a storage-related operation should like this should leave the pod completely unusable or if sync should continue??  Maybe it's too far gone at this point.

## Expected behavior

Push should succeed, and ServiceBinding info should be applied to new pod.

## Any logs, error output, etc?

See above.

# Notes

1. It seems there's a timing issue since I can bypass the problem by running in the debugger setting breakpoints.  But I notice this problem every time seem running normally from the CLI.

2. My Go skills are weak, but I think I traced the problem to the `Push` [function](https://github.com/openshift/odo/blob/9237d8d21f4e99021cdaef94bd8b8bac922d33a0/pkg/storage/storage.go#L658-L715) in `storage.go`

The problem seems to be that the call to:
	storageClusterList, err := client.ListFromCluster()
doesn't return the storage in question.   It returns an empty list, so later in the function, we think we need to go create this PVC, but it already exists from the previous push.     

I think that has something to do with the previous pod being down and the new pod just starting up.   

## Acceptance Criteria (WIP)

- [ ] Add integration tests to create a link after adding storage to the odo component.

**Comment by dharmit** [comment]
As for `needs-info` label, we need to reproduce the problem and figure out how to go about fixing it.

**Comment by scottkurz** [comment]
@dharmit let me know if you need help recreating.. I just didn't bother copying/"merging" all the steps from the doc but this should be enough info.      

Like I was hinting at in my comment....while I'm not following every step of the logic,  maybe the code in:
  https://github.com/openshift/odo/blob/main/pkg/storage/kubernetes.go#L82

isn't going to work since the Pod is going down?

**Comment by feloy** [comment]
@scottkurz you are right, ListFromCluster is unable to get the PVC because it tries to get the information from a running Pod, but at this time no pod is actually running (because we have just created a serviceBinding that triggered a change on the Deployment, that makes the pod being restarting).

But it's not clear to me why `ListFromCluster` is looking the information into a running pod, instead of looking into the `Deployment`, which is much more stable than a pod. @mik-dass I can see you have written this piece of code, any thought?

**Comment by mik-dass** [comment]
The problem is when the link is created, the pod gets restarted. When we try to check the storage mounted on the pod, there is no pod and so ListFromCluster() https://github.com/openshift/odo/blob/b2ca2a81a03d076cf1c6d24c3991363d6f1124e4/pkg/storage/kubernetes.go#L85 reports no storage on the cluster. Thus we try to create a new storage which fails because the storage already exists on the cluster.

https://github.com/openshift/odo/pull/4905 will fix this issue as the pod restart due to linking happens at a later stage.

**Comment by dharmit** [comment]
@mik-dass @feloy can we not look for the PVC from the Deployment instead of looking at the Pod? The Pod spec is embedded into the Deployment spec, no?

> #4905 will fix this issue as the pod restart due to linking happens at a later stage.

My concern with this is that, for some reason, if we change the behaviour again (and we have had a lot of back and forth about the "flow" of creating resources while working on this PR, so we shouldn't rule out another change in flow), this bug will bite us again, no?

**Comment by feloy** [comment]
@dharmit yes you are right, this solution is not very robust. It could be better to get the PVC information without the need of a Pod, which is possible

**Comment by dharmit** [comment]
- [ ] Merge #4905 
- [ ] Merge #4954 
- [ ] Figure a robust solution that checks against a Deployment instead of a pod.

**Comment by dharmit** [comment]
/reopen 

@mik-dass is working on this.
