### ISSUE TITLE
cleanup odo init image from s2i

### ISSUE THREAD

**Issue by kadel** [openshift/odo#5202]
now when we removed all s2i hacks and workarounds in odo we should do the same with odo init image.
There is a lot of scripts that were used only for s2i, those can be removed now.

**Comment by valaparthvi** [comment]
Check the odo init image and make a checklist of the things that can be removed.

**Comment by mohammedzee1000** [comment]
The scope of this issue is as follows:

- [ ] Remove https://github.com/openshift/odo-init-image/blob/master/s2i-setup
- [ ] Remove s2i references in https://github.com/openshift/odo-init-image/blob/c7f471f78c162ee9b5e70ae90b9bc63ce223db52/assemble-and-restart#L10-L72
- [ ] Remove https://github.com/openshift/odo-init-image/blob/c7f471f78c162ee9b5e70ae90b9bc63ce223db52/Dockerfile#L49
- [ ] Bump image version atleast in Y stream to indicate breaking changes
- [ ] Build and release new init image

**Comment by dharmit** [comment]
@feloy I have put this in your plate since you wanted to play with the release process. This issue requires releasing a new init image.

**Comment by dharmit** [comment]
Closing this. Only release of init image is remaining.

/close
