### ISSUE TITLE
Research and define `odo` development options

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#653]
As these options dictate what format the `.kube/odo` file will have we need to define what modes/options we will support:

- Deploying the same component to multiple applications
- Deploying the same component code with multiple component names
  - same application
  - different application
- Deploying the same application to multiple projects
- Deploying the same application to multiple clusters
  - same project
  - different project

**Comment by girishramnani** [comment]
@jorgemoralespou is this issue still relevant?

**Comment by jorgemoralespou** [comment]
Yes

**Comment by dharmit** [comment]
> As these options dictate what format the `.kube/odo` file will have we need to define what modes/options we will support:

Considering that issue was opened long time ago, I'm assuming that we're discussing `.odo/config.yaml` file. Please correct me if I'm wrong.

>     * Deploying the same component to multiple applications

At the moment, if we change the application of the project by doing `odo config set application <app-name>` and do `odo push`, we can deploy the same component to multiple applications.
>     * Deploying the same component code with multiple component names
>
>       * same application

Same as that for deploying same component to multiple applications, but for `odo config set name <component-name>`.
>       * different application

Combine the above two and you can do this as well.

>     * Deploying the same application to multiple projects

Just change the project name (`odo config set project <project-name>`) and this is achieved.

>     * Deploying the same application to multiple clusters
>       
>       * same project
>       * different project

`odo logout` and `odo login` to a different cluster helps deploy the same component to a different cluster. Unless `application` in this point something else.

If my understanding is correct, we are good to close this issue.

**Comment by Preeticp** [comment]
Needs exploration for docs and split into other doc user stories if required.

**Comment by dharmit** [comment]
@Preeticp I think we can add my responses in above comment to the docs. For example, in the docs section that talks about how to change the application name of current component, we can add that it can also be used to deploy same component to multiple applications. It's mostly the `odo config` that would need some update to the docs.

But, I'm not sure how important this exercise would be at this point in time. @kadel we're going to move to DevFiles soon enough. Does an exercise in updating documentation for something that's not brought up so far by end-users make sense? I think it's safe to close this.

**Comment by Preeticp** [comment]
For docs, devfile support will be top priority. If this issue becomes redundant once devfile support is in, and since no users have asked for this information yet, IMHO, we could close this issue.

**Comment by dharmit** [comment]
I believe most of the points raised by @jorgemoralespou are already taken care of at implementation level. However, since we're moving to DevFiles, we can skip the documentation.

Closing the issue.
