### ISSUE TITLE
Format services of the catalog discovered

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#660]
As the services (MySQL, ...) that the command `odo catalog list services` will display will come from different catalogs, then it is mandatory that when we will display the result that we indicate too that by example MySQL service is coming from ASB, idem for MySQL proposed by Openshift Template

[1] https://goo.gl/FdkXG1

**Comment by jorgemoralespou** [comment]
@cmoulliard why is this needed? As a user you don't mind which broker is providing the service, you only interact with the service-catalog which is one and only one for openshift. Then, broker can be many, but that should not matter at all.

**Comment by cmoulliard** [comment]
If the OpenShift's instance has been provisioned with 2 Service Brokers, then the user will most probably get 2 classes for by example MySQL Database

![screenshot 2018-08-28 18 49 12](https://user-images.githubusercontent.com/463790/44737754-220f4100-aaf3-11e8-9eef-adb27f2bbbea.png)

I agree that adding the Broker name as additional column is perhaps not the most valuable but that could help some teams/projects having qualifying a type of broker instead of another to select the appropriate class = service and plans. By example `MySQL (APB)` instead of `MySQL` as APB is related to Ansible PlayBook Format that we agreed to use ...

@jorgemoralespou Make sense ?

**Comment by cmoulliard** [comment]
> have two services with the same name coming even from the same catalog.

Good question. I will have a look as I'm not sure that this field `class.Spec.ExternalName` is unique and is used as a key (vs field of a record's db)

**Comment by cmoulliard** [comment]
Here is the info that I propose to show for each class discovered from the catalogs

| Name | Description | Versions |
|------|-------------|----------|
| dh-mssql-apb | Deployment of Microsoft SQL Server on Linux | N/A
| dh-mssql-remote-apb | Microsoft SQL Server Remote APB |  N/A
| dh-mariadb-apb |  Mariadb apb implementation  | 10.2
| dh-mariadb-apb | MariaDB database service, with persistent storage | 10.1, 10.2

**Comment by sspeiche** [comment]
I think it would be quite rare to have many duplicates in an OpenShift instance, hopefully the cluster-admin does a better job of curating the content and that we do a better job of setting up simple instances of the catalog.

Then it would an a rare exception instead of a common need to solve on the odo command line. The plan is to provide additional data about the classes in the future so that we could show more informative content: provider, provisioned on or off cluster, etc

**Comment by surajnarwade** [comment]
* Showing version is quite tricky because there's no field as `version` in `clusterserviceclass` or `clusterserviceplan`

* some of description are too long so, table looks very messy

* so, I added PR which shows only plans corresponding to classes. PR is here https://github.com/redhat-developer/odo/pull/687

* we can give more info about versions and descriptions in `odo catalog describe service` which is tracked here https://github.com/redhat-developer/odo/issues/689
