### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by noelo** [openshift/odo#764]
Add https/https proxy support for enterprise environments

**Comment by cdrage** [comment]
@noelo Mind explaining more in detail what you'd like added? I'm assuming https / proxy support for connecting to certain OpenShift clusters?

**Comment by cdrage** [comment]
I'm going to close this for now. If you can update us later that'd be great @noelo !

**Comment by greg-pendlebury** [comment]
> I'm assuming https / proxy support for connecting to certain OpenShift clusters?

Is this assumption reflective of the fact that there is no proxy support? I'm struggling to get this working. A simple login appears to partially work, but I think that is because the login is piggybacking off basic `oc login` functionality... then failing on simple queries:
![image](https://user-images.githubusercontent.com/2540158/65557790-dccc7580-df77-11e9-8a80-5261e02a9c30.png)

I have tried setting `all_proxy`, which I noticed in the source code, but this did nothing. The only (extremely hacky) solution I have found that works is to route the api calls through an SSH tunnel that bypasses the proxy altogether. Our proxy is extremely simple... no authentication, no exclusion list.

Running into the same problems in the IntelliJ plugin that wraps `odo`: https://github.com/redhat-developer/intellij-openshift-connector/issues/69 ... I was able to modify that plugin to at least bootstrap a GUI, but the underlying `odo` calls are all failing.

**Comment by kadel** [comment]
/open
this is a valid concern, odo should work with proxy settings

**Comment by greg-pendlebury** [comment]
Definitely not stale. Still very annoying that I have to open up the SSH tunnel daily for just this tool.

/remove-lifecycle stale

**Comment by dharmit** [comment]
@mohammedzee1000 going to make a note here about the approach he's going to follow the problem. We have all the other info we need.

**Comment by mohammedzee1000** [comment]
It looks like the proxy server is not being taken into account. I am investigating how `oc login` handles this as it seems to work.
Another option is to use the proxy envs `HTTP_PROXY` and `HTTPS_PROXY`.

I am taking @amitkrout help to setup a proxy env which should be available tomorrow, and then should be able to present more concrete answers

**Comment by jeffmaury** [comment]
We did the proxy support in IntelliJ OpenShift Connector based on HTTPS_PROXY and seems odo is honoring this variable so I think it's ok

**Comment by mohammedzee1000** [comment]
Ok so I am still looking at how oc does it.

Other that that, what we could do with env is:

1. Document users to set the env or
1. Have a preference for proxy, for eg `OPENSHIFT_PROXY`. If it is set then we set env before running a command, do the command and then unset the env automatically

**Comment by stlaz** [comment]
Do 1., don't do 2. The whole world (go, Python, cURL are examples that I know of) is using HTTP(S)_PROXY env vars, don't try to be special.

**Comment by mohammedzee1000** [comment]
I kind of agree with @stlaz here. What i want though is to confirm this is what oc does?

**Comment by mohammedzee1000** [comment]
> > I'm assuming https / proxy support for connecting to certain OpenShift clusters?
> 
> Is this assumption reflective of the fact that there is no proxy support? I'm struggling to get this working. A simple login appears to partially work, but I think that is because the login is piggybacking off basic `oc login` functionality... then failing on simple queries:
> ![image](https://user-images.githubusercontent.com/2540158/65557790-dccc7580-df77-11e9-8a80-5261e02a9c30.png)
> 
> I have tried setting `all_proxy`, which I noticed in the source code, but this did nothing. The only (extremely hacky) solution I have found that works is to route the api calls through an SSH tunnel that bypasses the proxy altogether. Our proxy is extremely simple... no authentication, no exclusion list.
> 
> Running into the same problems in the IntelliJ plugin that wraps `odo`: [redhat-developer/intellij-openshift-connector#69](https://github.com/redhat-developer/intellij-openshift-connector/issues/69) ... I was able to modify that plugin to at least bootstrap a GUI, but the underlying `odo` calls are all failing.

@greg-pendlebury can you verify if setting `HTTP_PROXY` and `HTTPS_PROXY` to your proxy server fixes your problem?

**Comment by mohammedzee1000** [comment]
@stlaz this is what lead me to consider further investigation ^

**Comment by greg-pendlebury** [comment]
@mohammedzee1000 no they do not. I definitely have those set because they are what let `oc` work the first place. It is `odo` functions that then proceed to fail after `oc` logs in.

I have just retested and confirmed it isn't working using v1.0.0-beta5 (quite old), but I haven't upgraded since I've never seen movement on these issues. Do you think this has been resolved elsewhere?

**Comment by greg-pendlebury** [comment]
FWIW, I just upgraded and tested v1.2.3 and it still doesn't support proxies (that I can see). `oc` works in this terminal (through `HTTP(S)_PROXY`) but not `odo`

**Comment by mohammedzee1000** [comment]
Well we do piggyback of client-go for all cluster activity. So the fact that it behaviour is really weird. @stlaz do you know anything about this?

**Comment by jeffmaury** [comment]
For me odo supports proxy.
Here what I did:
- started CRC on my Windows laptop
- modified the Windows /hosts so that api.crc.testing is resolved to 127.0.0.1
- started tinyproxy using docker and modified the container hosts to that api.crc.testing is resolved to CRC IP
- set HTTPS_PROXY to localhost:8888
- with odo created a component, pushed it, added an URL and checked my microservices API works ok
- stopped the tinyproxy
- ensure odo commands are now failing

**Comment by mohammedzee1000** [comment]
This is really strange indeed. I got feedback from openshift team. `oc` also uses client-go and according to them, 

```
Both oc and kubectl are heavy users of client-go and AFAIR we don't have any special code for handling proxies. As long as you use transport which allows injecting these from env vars you should be good
```

**Comment by mohammedzee1000** [comment]
@greg-pendlebury maybe we need to check is something different in you env?

**Comment by mohammedzee1000** [comment]
Would you be willing to share the information about your env such as your env variables when you run the command etc. If you are scared that you will leak any dangerous information, then feel free to send it to my redhat email `moahmed@redhat.com`. You can encrypt it using my gpg [key](http://keys.gnupg.net/pks/lookup?search=mohammed.zee1000%40gmail.com&fingerprint=on&op=index)

**Comment by mohammedzee1000** [comment]
Based on email communication:

It looks like it works fine for @greg-pendlebury with `http_proxy` and `https_proxy` when he did it in an environment where a second path existed to reach the cluster via his internet connection.

The environment where he faced the problem was basically `airgapped` wtth proxy being the only way to reach the cluster. We will likely need to account for this

**Comment by mohammedzee1000** [comment]
I have been trying to setup things on our internal openstack instance, where we already have an openshift cluster to try this out myself, but I have been hitting issues so far

What I am looking to setup (explain is representational):

### Proxy node
 - Network
   - n1=shared network that can access outside world
   - n2=private network
 - squid proxy setup to allow all requests

### Test Node
 - Network
   - n2=private network
 - oc and odo cli
 - http_proxy, https_proxy, all_proxy set to `Proxy Node`

**Comment by mohammedzee1000** [comment]
Ok I have a setup

```
# On the squid proxy node
$ squidclient http://squid.nlanr.net/
HTTP/1.1 200 OK
Date: Mon, 10 Aug 2020 08:56:35 GMT
Server: Apache/2.4.25 (Debian)
Content-Length: 6918
Vary: Accept-Encoding
Content-Type: text/html; charset=ascii
X-Cache: MISS from test
X-Cache-Lookup: HIT from <redacted>:3128
Via: 1.1 test (squid/4.11)
Connection: close

<html>

<head>
<title>NLANR -- National Laboratory for Applied Network Research</title>
</head>
...
# From the test node
ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 192.168.1.210 icmp_seq=1 Destination Host Unreachable
From 192.168.1.210 icmp_seq=2 Destination Host Unreachable
From 192.168.1.210 icmp_seq=3 Destination Host Unreachable

$ export HTTP_PROXY=https://<redacted>:3128
$ export HTTPS_PROXY=https://<redacted>:3128
$ export http_proxy=https://<redacted>:3128
$ export https_proxy=https://<redacted>:3128
$ odo login -u <redacted> -p <redacted> https://redacted # ran this on a different computer to ensure isolation
# Copy kubeconfig content to proxy machine

```

**Comment by mohammedzee1000** [comment]
Unable to reproduce. Seems like a env specific problem.

If you still face this problem, please reopen
/close
