### ISSUE TITLE
[RFE] Confusing entity name used to list the images to be used to build/run an application

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#838]
The following command is really confusing as I expect to list the components already registered for the different applications and not the s2i build/run images

```
odo catalog list components
NAME        PROJECT       TAGS
dotnet      openshift     2.0,latest
httpd       openshift     2.4,latest
nginx       openshift     1.10,1.12,1.8,latest
nodejs      openshift     0.10,10,4,6,8,8-RHOAR,latest
perl        openshift     5.16,5.20,5.24,5.26,latest
php         openshift     5.5,5.6,7.0,7.1,latest
python      openshift     2.7,3.3,3.4,3.5,3.6,latest
ruby        openshift     2.0,2.2,2.3,2.4,2.5,latest
wildfly     openshift     10.0,10.1,11.0,12.0,13.0,8.1,9.0,latest
```

The word `components` should be renamed to `builders` or `images` or a best word find.
Make sense @jorgemoralespou  @kadel @geoand ?

```
odo catalog list images | builders | ....
```

**Comment by jorgemoralespou** [comment]
Components in fact means something that can hold your application. This is
by definition what you're assembling. @cmoulliard also defined it this way
in his application definition slides.

This could be component type or runtime, maybe the latter.

The name builder reflects that it can build. This don't need to be true, or
soon will not need to be true, since you will be able to use just a runtime
image. That the component type is a builder, is decoration.

Image gives information about the underlying implementation which we're
trying to avoid.

If we rename this, we need to revisit the rest of the experience where this
can also happen. I could agree to name it "runtime".

**Comment by cmoulliard** [comment]
Finding the appropriate `word` is horribly complex ;-). As we still relying on s2i images which can be used to do the build's process (compile and generate code used by the build process to create a  docker image) AND by the run process to launch the application

As the purpose of this catalog is to list the languages/runtimes that a developer or architect will use to launch finally an application, using `runtime` is perhaps not a bad idea even if that will hurt `php, perl, donet`. 

```
odo catalog list runtimes
NAME        PROJECT       TAGS
dotnet      openshift     2.0,latest
httpd       openshift     2.4,latest
nginx       openshift     1.10,1.12,1.8,latest
nodejs      openshift     0.10,10,4,6,8,8-RHOAR,latest
perl        openshift     5.16,5.20,5.24,5.26,latest
php         openshift     5.5,5.6,7.0,7.1,latest
python      openshift     2.7,3.3,3.4,3.5,3.6,latest
ruby        openshift     2.0,2.2,2.3,2.4,2.5,latest
wildfly     openshift     10.0,10.1,11.0,12.0,13.0,8.1,9.0,latest
```

**Comment by dharmit** [comment]
At the moment, the word "component" has become a centrepiece to odo. So I don't think we're going to change `odo catalog list components` to something else.
